### ISSUE TITLE
Error when changing the dataset using state

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#10537]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=31491&p=160372#p160372)

Attached is an example with the error, tried to set `syncDataOnLoad: false`, but the issue persists.

[gantt-react-vite-basic.zip](https://github.com/user-attachments/files/18241292/gantt-react-vite-basic.zip)

"Hi,
I’m experiencing an issue while updating Gantt task data (when the tasks are segmented).

The data changes dynamically (via filtering), but after the second update, I encounter the following error:

Transaction.js:83 Uncaught (in promise) Error: Unknown identifier ModelClass-fb37e228-8396-4a41-acd2-b3284a932ff7.$.manuallyScheduled
    at throwUnknownIdentifier (Transaction.js:83:9)
    at EngineTransaction.onReadIdentifier (Graph.js:133:9)

I’ve created a simple project example to help you reproduce the issue:
- Click on “Change the data for the first time” – the data updates correctly.
- Click on “Change the data for the second time” – an error is thrown.

Please let me know if my project is missing any configuration or if there’s a way to fix this issue."

**Comment by canonic-epicure** [comment]
As Tasnim pointed on the forum, disabling `syncDataOnLoad` for task store fixes the issue:
```
  const ganttProject = useMemo(
    () => ({
      autoLoad: true,
      startDate: "2024-02-02",
      endDate: "2025-02-25",
      autoSetConstraints: true,
      taskStore: {
        syncDataOnLoad : false,
        keepExpandedOnLoad: true,
      },
    }),
    []
  );
```
This can be used as a temporary workaround.
