### ISSUE TITLE
Enable yarn support for installing packages

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#2392]
`@bryntum/gantt` package can be installed via npm, but yarn throws error.
```
node 14.2.0
yarn 1.17.3
npm 6.14.4
```

**Comment by bmblb** [comment]
```
Yarn version: 
  1.22.10

Node version: 
  14.2.0

Platform: 
  win32 x64

Trace: 
  TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
      at Function.from (buffer.js:331:9)
      at Object.fromHex (D:\soft\nvm\v14.2.0\node_modules\yarn\lib\cli.js:32678:14)
      at NpmResolver.<anonymous> (D:\soft\nvm\v14.2.0\node_modules\yarn\lib\cli.js:50710:73)
      at Generator.next (<anonymous>)
      at step (D:\soft\nvm\v14.2.0\node_modules\yarn\lib\cli.js:310:30)
      at D:\soft\nvm\v14.2.0\node_modules\yarn\lib\cli.js:321:13
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by SergeyMaltsev** [comment]
Yarn support added to NPM server.

To access Bryntum repository with yarn first use authorization with npm.
```
npm config set @bryntum:registry https://npm.bryntum.com
npm login --registry=https://npm.bryntum.com
```

After you have been authorized with npm you will be able to install packages with yarn.
**NO NEED TO LOGIN** to repository with yarn.

Use this to install from package.json
```
yarn install
```

And this to add something new
```
yarn add @bryntum/grid
```
