### ISSUE TITLE
Vue-3 should support nullish coalescing operator

### ISSUE THREAD

**Issue by pmiklashevych** [bryntum/support#2872]
See npm/templates/frameworks/vue/projects/pkgName/src/WrapperHelper.js
```
store.syncDataOnLoad = store.syncDataOnLoad ?? true;
```

Try to build and run Grid/tests/examples/frameworks/vue-3/vue-renderer.t.js demo

```
ERROR  Failed to compile with 1 error                                                                                                                                                                                                
error  in ./node_modules/@bryntum/grid-vue-3/src/WrapperHelper.js
Module parse failed: Unexpected token (134:65)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|                     // Set `syncDataOnLoad` to `true` by default
|                     // TODO: remove when https://github.com/bryntum/support/issues/2764 is done
>                     store.syncDataOnLoad = store.syncDataOnLoad ?? true;
| 
|                     store.relayAll(instance, dataStores[storeName]);
 @ ./node_modules/@bryntum/grid-vue-3/index.js 5:0-32
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/App.vue?vue&type=script&lang=js
 @ ./src/App.vue?vue&type=script&lang=js
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./src/main.js
 ERROR  Build failed with errors.
Error: Command failed: npm run build
    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at execute (/Users/pmiklashevich/Sites/Bryntum/bryntum-suite/scripts/tasks/frameworks.js:76:13)
    at buildNpm (/Users/pmiklashevich/Sites/Bryntum/bryntum-suite/scripts/tasks/frameworks.js:126:13)
    at build (/Users/pmiklashevich/Sites/Bryntum/bryntum-suite/scripts/tasks/frameworks.js:155:17)
    at demo (/Users/pmiklashevich/Sites/Bryntum/bryntum-suite/scripts/tasks/frameworks.js:262:17)
    at opt.roots.forEach.examplesFolder (/Users/pmiklashevich/Sites/Bryntum/bryntum-suite/scripts/tasks/frameworks.js:238:17)
    at Array.forEach (<anonymous>)
    at iterateDemos (/Users/pmiklashevich/Sites/Bryntum/bryntum-suite/scripts/tasks/frameworks.js:183:19)
    at buildDemos (/Users/pmiklashevich/Sites/Bryntum/bryntum-suite/scripts/tasks/frameworks.js:244:9)
BUILD Failed: frameworks/vue-3/javascript/vue-renderer
Skipped 24 demo(s)
Failed 1 demo(s)
frameworks/vue-3/javascript/vue-renderer
Writing log to .temp/build-error.log
```

Used old style to workaround it.

Note, adding nullish coalescing operator to the demo code breaks the compilation either.

**Comment by SergeyMaltsev** [comment]
Supported in vue-3-vite
In latest 5.6.0 release.
Grid/examples/frameworks/vue-3-vite/basic
