### ISSUE TITLE
MS Project import fails for MPX files using wk duration unit

### ISSUE THREAD

**Issue by arcady-zherdev** [bryntum/support#3898]
Reported here: https://www.bryntum.com/forum/viewtopic.php?p=98062

bryntum-msproject-reader.jar throws an exception:
```
net.sf.mpxj.MPXJException: Invalid file format
	at net.sf.mpxj.reader.UniversalProjectReader.readInternal(UniversalProjectReader.java:130)
	at net.sf.mpxj.reader.UniversalProjectReader.read(UniversalProjectReader.java:103)
	at net.sf.mpxj.reader.UniversalProjectReader.read(UniversalProjectReader.java:92)
	at bryntum.gantt.msprojectreader.Main.main(Main.java:64)
Caused by: net.sf.mpxj.MPXJException: Invalid file format
	at net.sf.mpxj.reader.UniversalProjectReader.readInternal(UniversalProjectReader.java:313)
	at net.sf.mpxj.reader.UniversalProjectReader.handleFile(UniversalProjectReader.java:532)
	at net.sf.mpxj.reader.UniversalProjectReader.readInternal(UniversalProjectReader.java:124)
	... 3 more
Caused by: net.sf.mpxj.MPXJException: Error reading file (failed at line 129)
	at net.sf.mpxj.mpx.MPXReader.read(MPXReader.java:192)
	at net.sf.mpxj.reader.UniversalProjectReader.readProjectFile(UniversalProjectReader.java:352)
	at net.sf.mpxj.reader.UniversalProjectReader.readInternal(UniversalProjectReader.java:210)
	... 5 more
Caused by: net.sf.mpxj.MPXJException: Invalid time unit wk
	at net.sf.mpxj.mpx.TimeUnitUtility.getInstance(TimeUnitUtility.java:61)
	at net.sf.mpxj.mpx.DurationUtility.getInstance(DurationUtility.java:88)
	at net.sf.mpxj.mpx.MPXReader.populateTask(MPXReader.java:1161)
	at net.sf.mpxj.mpx.MPXReader.parseRecord(MPXReader.java:392)
	at net.sf.mpxj.mpx.MPXReader.read(MPXReader.java:167)
	... 7 more
```

It starts working after replacing `wk` with `w` in the provided Test-01.mpx file.

**Comment by arcady-zherdev** [comment]
Reported to MPXJ author here: https://github.com/joniles/mpxj/issues/250

**Comment by arcady-zherdev** [comment]
As a temporary fix (until MPXJ issue is replied) will patch provided MPX-files right in the importer code.
