### ISSUE TITLE
Using chained `eventStore` caused an error

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#3995]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=19905&p=99021#p99021)

Not possible to use chained event store in the scheduler. 

To repro try to edit partners example. Remove partner property and make chained event store for 2nd scheduler. 

```
const eventStore = new EventStore({
        data: events
    }),
    eventStore2 = eventStore.makeChained();
```

An error in console:

```
Uncaught (in promise) TypeError: Cannot create property 'id' on boolean 'true'
    at ObjectHelper.js:303:24
    at Array.map (<anonymous>)
    at Function.transformNamedObjectToArray (ObjectHelper.js:300:71)
    at EventStore.setStoreData (Store.js:1375:33)
    at EventStore.setStoreData (AbstractPartOfProjectStoreMixin.js:88:37)
    at EventStore.set data (Store.js:1355:14)
    at EventStore.set data (SharedEventStoreMixin.js:455:20)
    at EventStore.set data [as data] (RecurringTimeSpansMixin.js:195:20)
    at ProjectModel.loadInlineData (SchedulerCoreProjectMixin.js:137:38)
    at ProjectModel.loadInlineData (ProjectModelMixin.js:556:22)
(anonymous) @ ObjectHelper.js:303
transformNamedObjectToArray @ ObjectHelper.js:300
setStoreData @ Store.js:1375
setStoreData @ AbstractPartOfProjectStoreMixin.js:88
set data @ Store.js:1355
set data @ SharedEventStoreMixin.js:455
set data @ RecurringTimeSpansMixin.js:195
loadInlineData @ SchedulerCoreProjectMixin.js:137
loadInlineData @ ProjectModelMixin.js:556
construct @ SchedulerCoreProjectMixin.js:89
construct @ ProjectModelMixin.js:430
construct @ ProjectModel.js:193
Base @ Base.js:380
ModelStm @ ModelStm.js:19
TreeNode @ TreeNode.js:25
Model @ Model.js:332
AbstractPartOfProjectGenericMixin @ AbstractPartOfProjectGenericMixin.js:10
Events @ Events.js:232
Delayable @ Delayable.js:166
Events @ Events.js:232
Delayable @ Delayable.js:166
CorePartOfProjectGenericMixin @ CorePartOfProjectGenericMixin.js:11
AbstractProjectMixin @ AbstractProjectMixin.js:21
SchedulerCoreProjectMixin @ SchedulerCoreProjectMixin.js:37
SchedulerCoreProjectMixin @ SchedulerCoreProjectMixin.js:29
ProjectModelMixin @ ProjectModelMixin.js:24
ProjectModel @ ProjectModel.js:135
changeProject @ ProjectConsumer.js:152
set @ Config.js:357
get @ Config.js:420
getConfig @ Base.js:843
startConfigure @ ProjectConsumer.js:64
setConfig @ Base.js:892
configure @ Base.js:821
construct @ Base.js:419
Base.construct @ shared.js:66
construct @ Localizable.js:154
construct @ Events.js:401
construct @ Widget.js:1428
construct @ TimelineZoomable.js:111
construct @ RecurringEvents.js:43
construct @ TimelineBase.js:405
construct @ EventNavigation.js:96
Base @ Base.js:380
Localizable @ Localizable.js:26
Events @ Events.js:232
Delayable @ Delayable.js:166
Identifiable @ Identifiable.js:24
Factoryable @ Factoryable.js:66
Widget @ Widget.js:277
Container @ Container.js:72
Toolable @ Toolable.js:27
Panel @ Panel.js:101
Pluggable @ Pluggable.js:20
State @ State.js:30
GridElementEvents @ GridElementEvents.js:42
GridFeatures @ GridFeatures.js:99
GridNavigation @ GridNavigation.js:25
GridResponsive @ GridResponsive.js:67
GridSelection @ GridSelection.js:38
GridState @ GridState.js:33
GridSubGrids @ GridSubGrids.js:63
LoadMaskable @ LoadMaskable.js:12
GridBase @ GridBase.js:114
TimelineDateMapper @ TimelineDateMapper.js:16
TimelineDomEvents @ TimelineDomEvents.js:26
TimelineEventRendering @ TimelineEventRendering.js:13
TimelineScroll @ TimelineScroll.js:23
TimelineViewPresets @ TimelineViewPresets.js:33
TimelineZoomable @ TimelineZoomable.js:43
RecurringEvents @ RecurringEvents.js:16
TimelineBase @ TimelineBase.js:59
CrudManagerView @ CrudManagerView.js:16
SchedulerDom @ SchedulerDom.js:13
SchedulerDomEvents @ SchedulerDomEvents.js:12
ProjectConsumer @ ProjectConsumer.js:15
SchedulerStores @ SchedulerStores.js:17
SchedulerScroll @ SchedulerScroll.js:24
SchedulerState @ SchedulerState.js:33
SchedulerEventRendering @ SchedulerEventRendering.js:34
SchedulerRegions @ SchedulerRegions.js:12
EventSelection @ EventSelection.js:13
Delayable @ Delayable.js:166
EventNavigation @ EventNavigation.js:16
SchedulerBase @ SchedulerBase.js:90
Scheduler @ Scheduler.js:389
(anonymous) @ app.js:126
Show 57 more frames
```

**Comment by knobel-dk** [comment]
Same problem in another thread https://forum.bryntum.com/viewtopic.php?p=114064#p114064

**Comment by chuckn0rris** [comment]
Another report here https://forum.bryntum.com/viewtopic.php?p=115866#p115866

**Comment by ExtAnimal** [comment]
I just added this test and it passes:

```
    t.iit('Should be able to share one CrudManager and drag an event', async t => {
        t.mockUrl('share-crudmanager', {
            delay        : 2000,
            responseText : JSON.stringify({
                success   : true,
                resources : {
                    rows : [{
                        id   : 1,
                        name : 'Resource 1'
                    }, {
                        id   : 2,
                        name : 'Resource 2'
                    }]
                },
                events : {
                    rows : [{
                        id         : 1,
                        resourceId : 1,
                        name       : 'Resource 1 Event',
                        startDate  : '2018-02-01',
                        endDate    : '2018-02-02'
                    }, {
                        id         : 2,
                        resourceId : 2,
                        name       : 'Resource 2 Event',
                        startDate  : '2018-02-02',
                        endDate    : '2018-02-03'
                    }]
                }
            })
        });

        const config = {
            height              : '50%',
            appendTo            : document.body,
            startDate           : new Date(2018, 1, 1),
            endDate             : new Date(2018, 1, 5),
            style               : 'margin-bottom:1em',
            useInitialAnimation : false
        };

        // First Scheduler to see only resources with ids < 2
        firstScheduler = t.getScheduler({
            id          : 'firstScheduler',
            crudManager : {
                autoLoad  : true,
                autoSync  : false,
                transport : {
                    load : {
                        url : 'share-crudmanager'
                    }
                }
            },
            ...config
        });

        // First Scheduler to see only resources with ids > 1
        secondScheduler = t.getScheduler({
            id      : 'secondScheduler',
            partner : firstScheduler,
            project : {
                eventStore    : firstScheduler.eventStore.chain(),
                resourceStore : firstScheduler.resourceStore.chain()
            },
            ...config
        });

        // Both Schedulers must show their events
        await t.waitForSelector('#secondScheduler .b-sch-event-wrap[data-event-id="1"]');
        await t.waitForSelector('#firstScheduler .b-sch-event-wrap[data-event-id="1"]');

        // Both loaded events show in each Scheduler
        t.selectorCountIs('#firstScheduler .b-sch-event-wrap', 2);
        t.selectorCountIs('#secondScheduler .b-sch-event-wrap', 2);

        // Drag of an event must work error free
        await t.dragBy({
            source : '#firstScheduler .b-sch-event-wrap[data-event-id="1"]',
            delta  : [200, 0]
        });

        await t.waitForAnimations();
    });
```

**Comment by chuckn0rris** [comment]
@ExtAnimal try to drag in second scheduler
