### ISSUE TITLE
Error while setting constraint type for a milestone on initial data load

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4066]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=20108&p=99723#p99723)

Try to set a constraint type "Must start on" for a milestone (child task). See an error in console.

```
const project = window.project = new ProjectModel({

});

project.loadInlineData({
    "eventsData": [
      {
        "id": "PepchXV3SViTswgpYSz0MQ",
        "name": "COMMERCIALISATION",
        "startDate": "2021-04-29T10:00:00.000Z",
        "endDate": "2021-05-01T10:00:00.000Z",
        "percentDone": 0,
        "expanded": true,
        "entities": "CodeEtape:ET00000003",
        "children": [
          {
            "id": "4kaCfYtjSsWLEp-EpFf2wA",
            "name": "Signature promesse Client ",
            "startDate": "2021-04-29T10:00:00.000Z",
            "endDate": "2021-04-29T10:00:00.000Z",
            "percentDone": 0,
            "expanded": false,
            "entities": "CodeEtape:ET00000003:CodeAction:ACT00000847",
            "milestone": true,
            "treso": true,
            "vente": true,
            "rollup": true
          }
        ],
        "rollup": true
      }
    ],
    "dependenciesData": [

    ]
  });

    const gantt = new Gantt({
        appendTo : 'container',

        dependencyIdField : 'wbsCode',

        project,
        columns : [
            { type : 'wbs' },
            { type : 'name', width : 250 }
        ],

        columnLines : false,

        features : {

            labels      : {
                left : {
                    field  : 'name',
                    editor : {
                        type : 'textfield'
                    }
                }
            }

        }
    });

```

```
Revision.js:18 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'get')
    at EngineRevision.getLatestEntryFor (Revision.js:18:42)
    at EngineTransaction.readPrevious (Transaction.js:316:49)
    at EngineTransaction.readCurrentOrProposedOrPrevious (Transaction.js:302:21)
    at TemplateClass.getFromGraph (ModelFieldAtom.js:73:56)
    at TaskModelEx.get (Entity.js:249:48)
    at NewTaskRendering.getTaskBox (NewTaskRendering.js:106:94)
    at NewTaskRendering.renderer (NewTaskRendering.js:669:23)
    at TimeAxisColumn.internalRenderer (TimeAxisColumn.js:346:42)
    at Row.renderCell (Row.js:691:39)
    at Row.render (Row.js:550:23)
getLatestEntryFor @ Revision.js:18
readPrevious @ Transaction.js:316
readCurrentOrProposedOrPrevious @ Transaction.js:302
getFromGraph @ ModelFieldAtom.js:73
get @ Entity.js:249
getTaskBox @ NewTaskRendering.js:106
renderer @ NewTaskRendering.js:669
internalRenderer @ TimeAxisColumn.js:346
renderCell @ Row.js:691
render @ Row.js:550
renderFromRow @ RowManager.js:939
refresh @ RowManager.js:1032
refreshRows @ GridBase.js:2973
refreshRows @ TimelineBase.js:1711
refresh @ TimelineBase.js:1655
(anonymous) @ TimelineBase.js:1766
runWithTransition @ TimelineBase.js:1743
refreshWithTransition @ TimelineBase.js:1766
resumeRefresh @ GanttBase.js:609
internalOnProjectRefresh @ GanttStores.js:144
trigger @ Events.js:1251
finalizeCommitAsync @ Replica.js:189
doCommitAsync @ Graph.js:349
setTimeout (async)
(anonymous) @ Replica.js:191
finalizeCommitAsync @ Replica.js:190
doCommitAsync @ Graph.js:349
await in doCommitAsync (async)
(anonymous) @ Graph.js:331
Promise.then (async)
commitAsync @ Graph.js:330
commitAsync @ Replica.js:157
autoCommitHandler @ Graph.js:100
setTimeout (async)
scheduleAutoCommit @ Graph.js:439
write @ Graph.js:562
writeToGraph @ Identifier.js:54
writeToGraph @ ModelFieldAtom.js:82
set @ Entity.js:252
onFieldChange @ Container.js:952
onFieldChange @ FormTab.js:59
(anonymous) @ Widget.js:5884
eachAncestor @ Widget.js:4702
triggerFieldChange @ Widget.js:5882
onValueCollectionChange @ Combo.js:1788
trigger @ Events.js:1251
splice @ Collection.js:676
onItemClick @ List.js:701
onClick @ List.js:639
handler @ EventHelper.js:531
Revision.js:18 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'get')
    at EngineRevision.getLatestEntryFor (Revision.js:18:42)
    at EngineTransaction.hasIdentifier (Transaction.js:399:57)
    at EngineReplica.hasIdentifier (Graph.js:544:39)
    at TaskModelEx.writeEndDate (HasDateConstraintMixin.js:56:35)
    at EngineTransaction.write (Transaction.js:356:26)
    at EngineReplica.write (Graph.js:560:32)
    at TemplateClass.writeToGraph (Identifier.js:54:19)
    at TemplateClass.writeToGraph (ModelFieldAtom.js:82:41)
    at TaskModelEx.set (Entity.js:252:41)
    at Function.assign (<anonymous>)
```

**Comment by matsbryntse** [comment]
Not reproducible
