### ISSUE TITLE
Error + white screen after failed deletion in React demo

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#4311]
https://bryntum.com/examples/gantt/frameworks/react/javascript/basic/build/
Double click a cell to show a React editor in Draggable column (broken in 5.0.1)
Click Edit button in Edit column
Press Delete in task editor

DOM is completely cleared
```
rootcause-full.js:10 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ca (https://bryntum.com/examples/gantt/frameworks/react/javascript/basic/build/static/js/2.f8a7df0d.chunk.js:74:417201)
    at fl (https://bryntum.com/examples/gantt/frameworks/react/javascript/basic/build/static/js/2.f8a7df0d.chunk.js:74:430460)
    at t.unstable_runWithPriority (https://bryntum.com/examples/gantt/frameworks/react/javascript/basic/build/static/js/2.f8a7df0d.chunk.js:74:451213)
    at Wi (https://bryntum.com/examples/gantt/frameworks/react/javascript/basic/build/static/js/2.f8a7df0d.chunk.js:74:375344)
    at hl (https://bryntum.com/examples/gantt/frameworks/react/javascript/basic/build/static/js/2.f8a7df0d.chunk.js:74:428318)
    at Ja (https://bryntum.com/examples/gantt/frameworks/react/javascript/basic/build/static/js/2.f8a7df0d.chunk.js:74:424449)
    at https://bryntum.com/examples/gantt/frameworks/react/javascript/basic/build/static/js/2.f8a7df0d.chunk.js:74:375635
    at t.unstable_runWithPriority (https://bryntum.com/examples/gantt/frameworks/react/javascript/basic/build/static/js/2.f8a7df0d.chunk.js:74:451213)
    at Wi (https://bryntum.com/examples/gantt/frameworks/react/javascript/basic/build/static/js/2.f8a7df0d.chunk.js:74:375344)
    at Gi (https://bryntum.com/examples/gantt/frameworks/react/javascript/basic/build/static/js/2.f8a7df0d.chunk.js:74:375580)

```

**Comment by chuckn0rris** [comment]
Dupe https://github.com/bryntum/support/issues/4308
