### ISSUE TITLE
Error when using store instance in `ProjectModel` definition

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4392]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=20675&p=102650#p102650)

```
import { EventModel, EventStore, SchedulerPro } from '@bryntum/schedulerpro';

const parent = new EventModel({ name: 'parent1', children: [] });
const child1 = new EventModel({ name: 'child1'});
const child2 = new EventModel({ name: 'child2'});
const child3 = new EventModel({ name: 'child3' });

parent.appendChild([child1, child2, child3]);

const ownEventStore = new EventStore({
  tree: true
});
const scheduler = new SchedulerPro({
  project: {
    eventStore: ownEventStore
  }
});
scheduler.eventStore.add(parent);
```

gives error 

```
core.mjs:6495 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'addToBucket')
TypeError: Cannot read properties of undefined (reading 'addToBucket')
    at TemplateClass.enterGraph (schedulerpro.module.js:184559:11)
    at EngineTransaction.addIdentifier (schedulerpro.module.js:182403:16)
    at EngineTransaction.addIdentifier (schedulerpro.module.js:186080:18)
    at EngineReplica.addIdentifier (schedulerpro.module.js:183454:28)
    at schedulerpro.module.js:184162:17
    at Map.forEach (<anonymous>)
    at EntityMeta.forEachField (schedulerpro.module.js:183827:20)
    at EventModel.enterGraph (schedulerpro.module.js:184160:20)
    at EngineReplica.addEntity (schedulerpro.module.js:183884:12)
    at EventModel.joinProject (schedulerpro.module.js:185761:25)
    at resolvePromise (zone.js:1255:1)
    at zone.js:1162:1
    at asyncGeneratorStep (asyncToGenerator.js:6:1)
    at _next (asyncToGenerator.js:25:1)
    at ZoneDelegate.invoke (zone.js:400:1)
    at Object.onInvoke (core.mjs:25877:33)
    at ZoneDelegate.invoke (zone.js:399:1)
    at Zone.run (zone.js:160:1)
    at zone.js:1318:1
    at ZoneDelegate.invokeTask (zone.js:434:1)
```

**Comment by canonic-epicure** [comment]
So the problem was caused by the fact, that if scheduler pro is used with the event tree store, the project instance becomes a root node of the store. However, the scheduler pro project class was missing the `HasChildrenMixin`, adding it has fixed the problem

**Comment by canonic-epicure** [comment]
The forum post also contains a report about another exception, extracted to #5420
