### ISSUE TITLE
[React] Error when change locale for gantt in routing page

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4457]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=1&t=20584&p=103281#p103281)
Test app
[gantt-test-case-master.zip](https://github.com/bryntum/support/files/8415616/gantt-test-case-master.zip)

Goto page with gantt,
try in console to change locale (ganttRef var is global)
```
ganttRef.localeManager.locale = "Ru"
```
See all ok, goto /Page in route, go back to /Gantt. see an error in console.
Same problem if change locale using UI

1. Open /gantt
2. go back to /page, click "Ru" button below routing buttons 
3. open /gantt 

```
Model.js:1983 Uncaught TypeError: s.trigger is not a function
    at Model.js:1983:1
    at Array.some (<anonymous>)
    at NameColumn.triggerBeforeUpdate (Model.js:1982:1)
    at NameColumn.inSet (Model.js:1411:1)
    at NameColumn.set (Model.js:1324:1)
    at NameColumn.set [as text] (DataField.js:252:1)
    at Objects.js:475:1
    at Array.reduce (<anonymous>)
    at Function.setPath (Objects.js:472:1)
    at NameColumn.localizeProperty (Localizable.js:180:1)
```

**Comment by jsakalos** [comment]
This is not a bug in our code but it is caused by React that is running the component over and over.
```
      <BryntumGantt
        ref={setGanttRef}
        columns={[{ text: "Name", field: "name", flex: 1 }]}
      />
```
The object literal of columns here passes always new instance of the columns array. However, `columns` is config-only option and cannot be changed at runtime. There is a warning about it in console:
```
react_devtools_backend.js:4026 BryntumGanttComponent development warning!
"columns" is a static config option for component constructor only. No runtime changes are supported!
Please check integration guide: https://bryntum.com/docs/grid/guide/Gantt/integration/react/guide 
    at BryntumGantt (http://localhost:3000/static/js/bundle.js:1895:5)
    at div
    at Gantt (http://localhost:3000/static/js/bundle.js:273:82)
    at Routes (http://localhost:3000/static/js/bundle.js:277940:5)
    at div
    at Router (http://localhost:3000/static/js/bundle.js:277873:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:276683:5)
    at App
    ...
```

It can be solved, for example, by keeping the `columns` array in state:
```
const Gantt = () => {
  const [columns] = useState([{ text: "Name", field: "name", flex: 1 }]);
  // ...
  return (
    <div className="gantt-wrapper-container">
      <BryntumGantt
        ref={setGanttRef}
        columns={columns}
      />
    </div>
  );
}
```

There is no warning or error in this case.

**Comment by jsakalos** [comment]
Reopening to investigate.

**Comment by jsakalos** [comment]
I have re-investigated it and it behaves as described above (Gantt version 5.1.1). Putting columns to state resolves the issue, however, we probably shouldn't crash even it they're not in state. The error originates in `Model.js`:
```
    triggerBeforeUpdate(changes) {
        return !this.stores.some(s => {
            return s.trigger('beforeUpdate', { record : this, changes }) === false;
        });
    }

```
