### ISSUE TITLE
[ANGULAR] Fullscreen error when request a fullscreen 

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4622]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=21281&p=105303#p105303)

Try to call this code
```
        this.schedulerComponent.instance.requestFullscreen();
```

See error in console: 
```
gantt.lite.umd.js:46083 Uncaught (in promise) TypeError: fullscreen error
    at Function.request (gantt.lite.umd.js:46083:12)
    at Button.onToggle (bryntum-gantt-angular.js:27:27)
    at Button.callback (gantt.lite.umd.js:7719:70)
    at Button.trigger (gantt.lite.umd.js:55087:27)
    at Button.updatePressed (gantt.lite.umd.js:66229:8)
    at Button.set (gantt.lite.umd.js:9219:13)
    at HTMLDocument.<anonymous> (bryntum-gantt-angular.js:31:1)
    at ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.mjs:25459:1)
    at ZoneDelegate.invokeTask (zone.js:405:1)
```

Try to reproduce it in custom-event-editor demo, dbl-click on any event and see that no popup shown after fullscreen mode enabled.

**Comment by SergeyMaltsev** [comment]
Not reproducible in `6.0.6`
https://bryntum.com/products/scheduler/examples/frameworks/angular/custom-event-editor/dist/custom-event-editor/
