### ISSUE TITLE
Bug in export function

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#4867]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=21648&p=107013#p107013)

Hello

I've found a bug in small windows when exporting.

When changing the size of the window and exporting we can get an error:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'top')
    at MultiPageExporter.buildPage (schedulerpro.module.js:43:12521)
    at MultiPageExporter.pagesExtractor (schedulerpro.module.js:43:15428)
    at pagesExtractor.next (<anonymous>)
    at MultiPageExporter.getPages (schedulerpro.module.js:43:5546)
    at async MultiPageExporter.export (schedulerpro.module.js:43:5268)
    at async PdfExport.export (schedulerpro.module.js:43:34389)
```

How to reproduce: 

Go to the example:
https://bryntum.com/examples/examples-scheduler/milestonelayout/

Set the code to the one in the txt example

Set the viewport to the size in the image below

![error_print.png](https://www.bryntum.com/forum/download/file.php?id=17854)

**Comment by bmblb** [comment]
This issue should be fixed by #4449 which would be merged to the master branch shortly after 5.1.0 release
