### ISSUE TITLE
Remove ViewPreset base property from example docs

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#5006]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=21947&p=108537#p108537)

Remove the **base** property in the example available at [Bryntum Docs](https://bryntum.com/docs/gantt/api/Scheduler/preset/ViewPreset)

In the documentation, we don't have that property, so in the TS examples, we can't use that demo because it'll trigger an error because of that non-existent property.

**Comment by FlowIT-JIT** [comment]
Why hasn't this been fixed? It's such an easy fix!

Also, extending viewpresets doesn't work unless 'headers' are defined. What's the purpose of extending when it doesn't work with all properties? The amount of bugs in this product is staggering.

```
const vp = new ViewPreset({
    id   : 'myPreset',
    name : 'My view preset',
    base : 'hourAndDay',

    timeResolution : {
        unit      : 'minute',
        increment : 15
    }
} as Partial<ViewPresetConfig> & { base: string /* Property 'base' is officially supported but missing in typedef */ });

PresetManager.add(vp);
```

Error thrown:

```
Uncaught TypeError: Cannot destructure property 'length' of 'headers' as it is undefined.
    at ViewPreset.normalizeUnits (gantt.module.js:138857:1)
    at ViewPreset.construct (gantt.module.js:138808:1)
    at new Base$1 (gantt.module.js:2575:1)
    at new ModelStm (gantt.module.js:18357:1)
    at new TreeNode (gantt.module.js:18628:1)
    at new ModelLink (gantt.module.js:19687:1)
    at new Model (gantt.module.js:21531:1)
    at new ViewPreset (gantt.module.js:138671:1)
    at GanttHooks.ts:217:24
    at commitHookEffectListMount (react-dom.development.js:23150:1)
```
