### ISSUE TITLE
Moved collapsed column doesn't have red text when drop is prohibited

### ISSUE THREAD

**Issue by SergeyMaltsev** [bryntum/support#5253]
Demo `Grid/examples/collapsible-columns/`

Browser: Chrome

### Steps

* Collapse first group
* Drag move over the last column

![image](https://user-images.githubusercontent.com/57486330/190376452-0772610f-5427-4aaf-b215-f4a813db8f5e.png)

P.S. In FireFox dragging column is not marked with red at all

Same can be seen in `Scheduler/examples/collapsible-columns/` demo

![image](https://user-images.githubusercontent.com/57486330/190381394-ade98932-e632-45b8-b82c-77f226f90b4c.png)

**Comment by matsbryntse** [comment]
Occasionally crashes
```

Uncaught RangeError: Maximum call stack size exceeded
    at ColumnStore.collectDescendants (StoreTree.js:294:23)
    at ColumnStore.collectDescendants (StoreTree.js:309:20)
    at ColumnStore.collectDescendants (StoreTree.js:309:20)
    at ColumnStore.collectDescendants (StoreTree.js:309:20)
    at ColumnStore.collectDescendants (StoreTree.js:309:20)
    at ColumnStore.collectDescendants (StoreTree.js:309:20)
    at ColumnStore.collectDescendants (StoreTree.js:309:20)
    at ColumnStore.collectDescendants (StoreTree.js:309:20)
    at ColumnStore.collectDescendants (StoreTree.js:309:20)
    at ColumnStore.collectDescendants (StoreTree.js:309:20)

```
