### ISSUE TITLE
`syncDataOnLoad` + `threshold`, scroll error

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#5706]
call stack 
```
RowManager.js:1118 Uncaught TypeError: Cannot read properties of undefined (reading 'id')
    at RowManager.jumpToPosition (RowManager.js:1118:53)
    at RowManager.warpIfNeeded (RowManager.js:1227:38)
    at RowManager.updateRenderedRows (RowManager.js:1263:32)
    at Grid.onGridVerticalScroll [as onGridVerticalScrollNow] (GridBase.js:2647:27)
    at Grid.<anonymous> (Delayable.js:897:39)
    at Grid.invoker (Delayable.js:101:24)
    at Delayable.js:499:57
```

video :

https://user-images.githubusercontent.com/75997756/205551425-79941e55-01ce-4d10-8e2a-511c61818d33.mp4

[Forum post](https://forum.bryntum.com/viewtopic.php?f=43&t=23163&p=114547#p114547)

I modified the basic demo in the examples page and added a syncDataOnLoad property with a 50% threshold. I updated the data to generate 100 rows and then scrolled the grid to the bottom. Then after 5 seconds I set the grid data to 1 record and it generates an error and the grid display becomes wacky.

```
import { Grid, DataGenerator } from '../../build/grid.module.js?463787';
import shared from '../_shared/shared.module.js?463787';

const dataArray = DataGenerator.generateData(100);

let grid = new Grid({

appendTo : 'container',

features : {
    group : false
},

// Headers will ripple on tap in Material theme
ripple : {
    delegate : '.b-grid-header'
},

store: {
    syncDataOnLoad: {
        threshold: '50%'
    }
},

columns : [
    {
        text   : 'Name',
        field  : 'name',
        flex   : 2,
        editor : {
            type     : 'textfield',
            required : true
        }
    }, {
        text  : 'Age',
        field : 'age',
        width : 100,
        type  : 'number'
    }, {
        text  : 'City',
        field : 'city',
        flex  : 1
    }, {
        text  : 'Food',
        field : 'food',
        flex  : 1
    }, {
        text     : 'Color (not sortable)',
        field    : 'color',
        flex     : 1,
        sortable : false,
        renderer({ cellElement, value }) {
            // renderer that sets text color = text
            cellElement.style.color = value;
            return value;
        }
    }
],

data : dataArray
});

grid.scrollRowIntoView(99);

setTimeout(() => {
    grid.data = DataGenerator.generateData(1);
}, 5000);

```

Any ideas?

Thanks,
Tim

**Comment by TMcKinley** [comment]
It looks like I'm still getting an error in RowManager.jumpToPosition

```
let accumulated = 0,
  targetIndex = 0;
  while (accumulated < top) {
    const record = store.getAt(targetIndex);
    accumulated += heightMap.get(record.id) + border;
    targetIndex++;
  }
```
The issue is that we just went from 100 rows to 2 rows so my top value is pretty high. I think the while loop needs to be restricted by the store count otherwise it just overflows. This was my override and it seems to work:

```
  while (accumulated < top && targetIndex < storeCount) {

  }
```
(the storeCount variable was defined earlier in that method).

Thanks,
Tim
