### ISSUE TITLE
Crash when deleting task in task editor

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#5793]
In advanced demo
edit a task in task editor
choose an invalid predecessor (such as the top level project node)
click Delete button 
```
GridNavigation.js:533 Uncaught RangeError: Maximum call stack size exceeded.
    at Grid.findFocusables (GridNavigation.js:533:46)
    at Grid.onGridBodyFocusIn (GridNavigation.js:456:65)
    at HTMLDivElement.handler (EventHelper.js:511:78)
    at DomHelper.focusWithoutScrolling (DomHelper.js:1554:21)
    at ModelCombo.focus (Widget.js:4463:23)
    at ModelCombo.focus (PickerField.js:508:15)
    at Editor.completeEdit (Editor.js:538:35)
    at CellEdit.finishEditing (CellEdit.js:915:60)
    at CellEdit.onEditorFocusOut (CellEdit.js:1325:26)
    at Editor.trigger (Events.js:1365:35)
```
<img width="1439" alt="Screenshot 2022-12-15 at 11 19 02" src="https://user-images.githubusercontent.com/218570/207833979-e786d5e1-09cb-4f30-9801-15747d263f4a.png">

**Comment by matsbryntse** [comment]
Not reproducible
