### ISSUE TITLE
renderer configuration for tree type column triggers an error

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#5920]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=43&t=23491&p=116338#p116338)

"trying to configure a renderer for a tree type column

```
{
                    text   : 'objectName',
                    field  : 'objectName',
                    width  : 400,
                    type   : 'tree',
                    renderer({ value, record }) {
                        if (record.isLeaf) {
                            return [
                                {
                                    tag       : 'img',
                                    className : 'avatar',
                                    src       : record.data.icon
                                },
                                record.data.objectName
                            ];
                        }
                        else {
                            return record.data.objectName;
                        }
                    },
                    //locked : true //Set locked to true then the column will be displayed on the left side of the grid
                }
```

fails with exception

```
{
    "stack": "Error: Failed to execute 'setAttribute' on 'Element': '0' is not a valid attribute name.\n    at ha.syncAttributes (http://localhost:8090/WEB7/WEBApp/3rdParty/Bryntum/grid.umd.min.js:10:346501)\n    at ha.performSync (http://localhost:8090/WEB7/WEBApp/3rdParty/Bryntum/grid.umd.min.js:10:344107)\n    at ha.insertElement (http://localhost:8090/WEB7/WEBApp/3rdParty/Bryntum/grid.umd.min.js:10:347964)\n    at ha.syncChildren (http://localhost:8090/WEB7/WEBApp/3rdParty/Bryntum/grid.umd.min.js:10:350087)\n    at ha.performSync (http://localhost:8090/WEB7/WEBApp/3rdParty/Bryntum/grid.umd.min.js:10:344169)\n    at ha.insertElement (http://localhost:8090/WEB7/WEBApp/3rdParty/Bryntum/grid.umd.min.js:10:347964)\n    at ha.syncChildren (http://localhost:8090/WEB7/WEBApp/3rdParty/Bryntum/grid.umd.min.js:10:350087)\n    at ha.performSync (http://localhost:8090/WEB7/WEBApp/3rdParty/Bryntum/grid.umd.min.js:10:344169)\n    at ha.sync (http://localhost:8090/WEB7/WEBApp/3rdParty/Bryntum/grid.umd.min.js:10:343648)\n    at Iv.renderCell (http://localhost:8090/WEB7/WEBApp/3rdParty/Bryntum/grid.umd.min.js:28:122917)"
}
```

configuring the renderer for a normal type column works"

**Comment by matsbryntse** [comment]
Not reproducible
