### ISSUE TITLE
An error on apply StateProvider state 

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#5975]
[Forum post](https://forum.bryntum.com/viewtopic.php?t=23390&start=10)
In attachments our basic app with some required changes. 
To reproduce, run the app, move splitter in Gantt a bit and reload the page. 

See console error:
```
gantt.module.js:119387 Uncaught TypeError: Cannot read properties of undefined (reading 'height')
    at Gantt.refreshTotalHeight (gantt.module.js:119387:1)
    at Gantt.onRowManagerChangeTotalHeight (gantt.module.js:119367:1)
    at RowManager.trigger (gantt.module.js:5954:1)
    at RowManager.estimateTotalHeight (gantt.module.js:112052:1)
    at RowManager.reinitialize (gantt.module.js:110938:1)
    at Gantt.resumeRefresh (gantt.module.js:225371:1)
    at Gantt.applyState (gantt.module.js:168884:1)
    at Gantt.applyState (gantt.module.js:223739:1)
    at set state [as state] (gantt.module.js:18356:1)
    at Gantt.loadState (gantt.module.js:18515:1)
    at Gantt.finalizeInit (gantt.module.js:18318:1)
    at Gantt.finalizeInit (gantt.module.js:115326:1)
    at Gantt.finalizeInit (gantt.module.js:117965:1)
    at Gantt.construct (gantt.module.js:44370:1)
    at Gantt.construct (gantt.module.js:167222:1)
    at Gantt.construct (gantt.module.js:167862:1)
    at Gantt.construct (gantt.module.js:169334:1)
    at Gantt.construct (gantt.module.js:174321:1)
    at Gantt.construct (gantt.module.js:225317:1)
    at new Base$1 (gantt.module.js:2624:1)
    at new Localizable (gantt.module.js:6634:1)
    at new Events (gantt.module.js:4986:1)
    at new Delayable (gantt.module.js:17020:1)
    at new Identifiable (gantt.module.js:18737:1)
    at new Factoryable (gantt.module.js:20518:1)
    at new KeyMap (gantt.module.js:42599:1)
    at new RTL (gantt.module.js:42810:1)
    at new Widget (gantt.module.js:43160:1)
    at new Container (gantt.module.js:49258:1)
    at new State (gantt.module.js:18311:1)
    at new Toolable (gantt.module.js:52702:1)
    at new Panel (gantt.module.js:54556:1)
    at new Pluggable (gantt.module.js:16777:1)
    at new GridElementEvents (gantt.module.js:112515:1)
    at new GridFeatures (gantt.module.js:113280:1)
    at new GridNavigation (gantt.module.js:113484:1)
    at new GridResponsive (gantt.module.js:114235:1)
    at new GridSelection (gantt.module.js:114376:1)
    at new GridState (gantt.module.js:115263:1)
    at new GridSubGrids (gantt.module.js:116829:1)
    at new LoadMaskable (gantt.module.js:65277:1)
    at new GridBase (gantt.module.js:117308:1)
    at new TimelineDateMapper (gantt.module.js:166025:1)
    at new TimelineDomEvents (gantt.module.js:166402:1)
    at new TimelineEventRendering (gantt.module.js:168125:1)
    at new TimelineScroll (gantt.module.js:168380:1)
    at new TimelineState (gantt.module.js:168830:1)
    at new TimelineViewPresets (gantt.module.js:166773:1)
    at new TimelineZoomable (gantt.module.js:167158:1)
    at new RecurringEvents (gantt.module.js:167838:1)
```
There is another component in the code that use different project init way and there is no error with it.

[basic.zip](https://github.com/bryntum/support/files/10445099/basic.zip)

**Comment by minderm** [comment]
Guys, I spent quite a lot of time researching and solving this problem, since this functionality is very important for our project.

After discovering the problem, the first thing I did was to see if the problem could be reproduced on the demo site, I was surprised when I saw that the demo worked perfectly. But the demo doesn't work with the React version of the component.

Then I decided to reproduce the work with StateProvider in examples where React is used. But examples with React only work locally, I had to build the example locally and transfer the logic from the example to it, with the work of StateProvider, and the problem reproduced!

I went ahead and started comparing how the React version and the JS version work. After a lot of research, it turned out that the React version uses the "adopt" parameter when initializing, and the JS example uses "appendTo". Another important point is that the project model must already be loaded and filled with data.

And so, after I made these changes to the demo version in the JS version, the problem was reproduced on the official site.
Steps to reproduce the bug:
1. Go to https://bryntum.com/products/gantt/examples/state/
2. Open Code editor
3. In the launch function
  - change appendTo to adopt
  - change project from 
  `project : {
            autoLoad  : true,
            transport : {
                load : {
                    url : '../_datasets/launch-saas.json'
                }
            }
        },`
  to 
`project : {
             tasks: [{
                                 "id" : 15,
                                 "name" : "Run tests",
                                 "percentDone" : 0,
                                 "startDate" : "2019-01-21",
                                 "rollup" : true
                                 "duration" : 2,
                                 "endDate" : "2019-01-23",
                                 "cost" : 5000,
                                 "priority" : "medium",
                             }]
         },`

It should turn out like in the screenshot, and the error will immediately reproduce
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/4593213/224465529-741c89ad-044e-48ab-afff-e4ddf946c3a5.png">


I will also add that to quickly solve the problem in the React version, you can force the adoptTo attribute with the DOM element Id into which the component will be rendered. Screenshot example below
<img width="592" alt="image" src="https://user-images.githubusercontent.com/4593213/224466052-afc4b4b5-0f1b-452d-bcf7-dea443634ccf.png">

**Comment by matsbryntse** [comment]
Thanks for amazing debug context, we'll get this fixed right away!
