### ISSUE TITLE
Filtering `timeAxis` to exclude weekends produces wrong results

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#6070]
### You could repro this here https://bryntum.com/products/scheduler/examples/basic
You need to use this code to filter timeAxis (It's going to filter the weekdays)
```
scheduler.timeAxis.filter(tick => ![0, 6].includes(tick.startDate.getDay()));
```

https://user-images.githubusercontent.com/75997756/215063617-92212bdf-f92e-4dab-a079-48dd262e8a00.mp4

Call stack
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'getTime')
    at DateHelper.add (DateHelper.js:1591:31)
    at Scheduler.calculateOptimalDateRange (TimelineZoomable.js:671:37)
    at Scheduler.zoomToLevel (TimelineZoomable.js:334:23)
    at Scheduler.zoomOut (TimelineZoomable.js:619:21)
    at Scheduler.onWheel (TimelineZoomable.js:752:57)
    at Scheduler.handler (EventHelper.js:517:78)
    at invoker (Delayable.js:101:24)
    at HTMLDivElement.throttleWrapFn (Delayable.js:804:21)
```

**Comment by matsbryntse** [comment]
Also blank screen if filtering right away in basic demo

`scheduler.timeAxis.filter(tick => ![0, 6].includes(tick.startDate.getDay()));
`
