### ISSUE TITLE
Cannot drop into collapsed group if store is filtered

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#6380]
Reproducible on grouping demo in grid:
1. enable row reorder feature, filter feature and change group feature definition to `group : true`
2. run demo, filter age column `> 14` and group by city
3. collapse first two groups
4. drag first row from the Moscow group into collapsed Dubai group
See exception:
```
Uncaught (in promise) Error: Collection move beforeItem parameter must be present in Collection
    at Collection.move (Collection.js:556:19)
    at Store.move (StoreCRUD.js:612:26)
    at Store.move (StoreGroup.js:230:15)
    at RowReorder.finalizeReorder (RowReorder.js:610:23)
    at RowReorder.onDrop (RowReorder.js:569:22)
```

UPD: important to group after filter. if you filter grouped store no exception is thrown

**Comment by bmblb** [comment]
Workaround is to return early from the `move` method if store is grouped. Groups will be updated if `reapplyFilterOnUpdate` is true. Otherwise record will stay old group but group field will no longer match the current group.

Problem is that we keep two collections in case of filtered dataset and main collection does not have any group information which breaks certain lookup. To allow any lookups we'd need to keep two grouped collections - complete and filtered. But that is a big task for now
