### ISSUE TITLE
Exception when moving cell editor with autoSync enabled

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#6459]
Reproducible only in angular application. Steps to reproduce on `angular/javascript/advanced` demo:
1. put syncUrl, mock it with this:
```
let counter = 100000;

AjaxHelper.mockUrl('/sync', (url, params, options) => {
    const body = JSON.parse(options.body);

    return {
        responseText : JSON.stringify({
            tasks : {
                rows : body.tasks.added.map(t => {
                    return {
                        $PhantomId : t.$PhantomId,
                        id         : counter++
                    };
                })
            }
        }),
        // delay : 20 * 2 // Sometimes it throws `unable to scroll %phantomid% into view (range 2-5)
        delay : 15 * 5
    };
});

```
2. set `autoSync: true`
3. add button to add record:
```
bbar : {
    items : {
        addBelow : {
            type : 'button',
            text : 'New task',
            async onClick() {
                //@ts-ignore
                const gantt = this.up('gantt');

                let added : TaskModel;

                if (gantt.selectedRecords.length === 1) {
                    added = await gantt.addTaskBelow(gantt.selectedRecord);
                }
                else {
                    added = await gantt.taskStore.rootNode.appendChild({ name : 'New task', duration : 1 });
                }

                if (added) {
                    await gantt.features.cellEdit.startEditing({ record : added, field : 'name' });
                }
            }
        }
    }
}
```
4. run the demo, click `new task` button twice
5. click on the name cell of the first added task.

See editor does not appear. When you double click you see an exception:
```
Uncaught Error: Uncaught (in promise): InvalidNodeTypeError: Failed to execute 'setEndBefore' on 'Range': the given Node has no parent.
Error: Failed to execute 'setEndBefore' on 'Range': the given Node has no parent.
    at Row.moveContentFromCell (gantt.module.js:109309:22)
    at Row.renderCell (gantt.module.js:109217:27)
    at Row.render (gantt.module.js:109047:17)
    at RowManager.renderFromRow (gantt.module.js:113854:11)
    at RowManager.refresh (gantt.module.js:113929:8)
    at Gantt.refreshRows (gantt.module.js:122796:18)
    at Gantt.refreshRows (gantt.module.js:174725:11)
    at Gantt.refresh (gantt.module.js:174682:14)
    at gantt.module.js:174775:41
    at Gantt.runWithTransition (gantt.module.js:174754:5)
    at resolvePromise (zone.js:1211:1)
    at zone.js:1118:1
    at zone.js:1134:1
    at asyncGeneratorStep (asyncToGenerator.js:6:1)
    at _throw (asyncToGenerator.js:29:1)
    at _ZoneDelegate.invoke (zone.js:372:1)
    at Object.onInvoke (core.mjs:25548:1)
    at _ZoneDelegate.invoke (zone.js:371:1)
    at Zone.run (zone.js:134:1)
    at zone.js:1275:1
```

**Comment by bmblb** [comment]
After recording a performance profile I can see differences in behavior between angular app and rect app (which does work). Angular uses `regeneratorRuntime` to transform async/await to regular functions. Problem is that generated code works different.

In react app code flows like this: cell loses focus -> editing is finished -> cellEdit calls `project.resumeAutoSync()` -> `project.sync` is called immediately and it starts a sync promise -> `finishEditing` method is called and gets executed in a single microtask.
In angular app it works like this: cell loses focus -> editing is finished -> cellEdit calls `resumeAutoSync()` -> `sync` is called -> `doCommitAsync` is called immediately, while `finishEditing` has not finished its work

It looks like `regeneratorRuntime` transforms code to an broken version which behaves completely different with vanilla version. It doesn't look like vanilla version can work as transformed version, so bug could only be reproduced if regenerator is present.

There are few workarounds which I see:
1. make CellEdit feature in Gantt stop suspend/resume auto sync (this change is actually what introduced bug in version 5.2.10)
2. make `resumeAutoSync` to call `scheduleSync` instead of `sync`

Attached are two profile recordings: angular (with a bug) and react (working normally).
[perf recording.zip](https://github.com/bryntum/support/files/11064535/perf.recording.zip)

@isglass @matsbryntse looking forward hearing your opinion on this.

**Comment by canonic-epicure** [comment]
As discussed in the Slack, I've replaced all usages of `obj instanceof Promise` with custom feature-testing function in the PR above.

**Comment by canonic-epicure** [comment]
That PR was chronogrpah-only and it was merged by other PRs.
