### ISSUE TITLE
Console error when using static tasks data

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#6635]
In advanced demo comment `transport` config, copy and paste `tasks` from launch-sass.json to project's `tasks` property.

```
project : {
    tasks : [
       // tasks array copied from launch-sass.json
    ]
}
```

Open app. See no Gantt rendered and error
```
litEventMixin.js:23 Uncaught TypeError: record.processSegmentsValue is not a function
    at ArrayDataField.segmentsConverter [as convert] (SplitEventMixin.js:23:60)
    at ModelClass.processData (Model.js:952:57)
    at ModelClass.construct (Model.js:812:31)
    at ModelClass.construct (TimeSpan.js:211:15)
    at ModelClass.construct (ChronoModelMixin.js:30:34)
    at ModelClass.construct (SplitEventMixin.js:76:19)
    at new Base (Base.js:380:12)
    at new ModelStm (ModelStm.js:19:26)
    at new TreeNode (TreeNode.js:89:9)
    at new ModelLink (ModelLink.js:91:26)
s
```

**Comment by chuckn0rris** [comment]
Wrong ticket. Fixed after rebuilt Engine locally.
