### ISSUE TITLE
Crash when adding task if refresh is suspended

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#6671]
In advanced demo:

`gantt.refreshSuspended = 1`

Click Create button to add a task 
```

idBase.js:2767 Uncaught (in promise) Error: Unable to scroll _generatedModelClass_8529cd1c-f7d4-4ead-9d6f-27440e3553c2 into view
    at Gantt.scrollRowIntoView (GridBase.js:2767:27)
    at GanttToolbar.onAddTaskClick (GanttToolbar.js:340:21)
    at async Promise.all (/bryntum-suite/gantt/examples/advanced/index 0)
s
```

**Comment by isglass** [comment]
Should be an easier way to repro, but this does it

```
t.xit('Should resume refresh after quick syncs', async t => {
        let syncCount = -1;

        let firstTask, lastTask;

        const syncResponses = [
            () => ({
                success : true,
                tasks   : {
                    rows : [
                        { $PhantomId : firstTask.id, id : 2 }
                    ]
                }
            }),
            () => ({
                success : true,
                tasks   : {
                    rows : [
                        { $PhantomId : lastTask.id, id : 3 }
                    ]
                }
            })
        ];

        t.mockUrl('sync', () => {
            return {
                delay        : 500 - syncCount * 100,
                responseText : JSON.stringify(syncResponses[syncCount]())
            };
        });

        const gantt = new Gantt({
            appendTo : document.body,
            project  : {
                loadUrl              : 'load',
                syncUrl              : 'sync',
                validateResponse     : false,
                // TODO
                silenceInitialCommit : false
            }
        });

        await gantt.project.commitAsync();

        const promises = [];

        firstTask = gantt.taskStore.add({ })[0];
        promises.push(gantt.project.sync());
        syncCount++;
        await gantt.project.commitAsync();
        // gantt.features.cellEdit.startEditing({ record : firstTask, field : 'name' });

        gantt.project.on('startApplyResponse', () => {
            gantt.features.cellEdit.startEditing({ record : firstTask, field : 'name' });
        });

        lastTask = gantt.taskStore.add({ })[0];
        promises.push(gantt.project.sync());
        syncCount++;

        await Promise.all(promises);

        t.is(gantt.refreshSuspended, 0);
    });```
