### ISSUE TITLE
Exception thrown when moving mouse after event drag create

### ISSUE THREAD

**Issue by canonic-epicure** [bryntum/support#7091]
https://github.com/bryntum/support/assets/72431/fcc12a95-d25c-4f0a-9c01-828af8cf4564

**Comment by canonic-epicure** [comment]
Added a workaround (possible even a fix) to the `Core/lib/Core/widget/Widget.js`, to be reviewed by someone in the context of that code.

```
        for (let followingEl = element.nextSibling, nextEl; followingEl; followingEl = nextEl) {
            nextEl = followingEl.nextSibling;
            if (parent.contains(followingEl) && !this.owns(followingEl)) {
                // this is a workaround for: https://github.com/bryntum/support/issues/7091
                // w/o this call, what happens is:
                // 1) `widgetsFrag.appendChild(followingEl)` starts and first thing it does
                // is removing the `followingEl` from the DOM
                // 2) As part of that process, the `blur` event is triggered
                // (surprisingly `blur` event is triggered synchronously in native DOM):
                //     document.addEventListener('blur', (e) => { debugger }, { capture : true })
                // 3) blur events handler removes/moves the `followingEl` from its previous parent somewhere else
                // 4) `widgetsFrag.appendChild(followingEl)` continues but since the element has been moved
                // in the middle it throws:
                // Uncaught (in promise) DOMException: Failed to execute 'appendChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
                //     at Tooltip.toFront (http://local/Bryntum/bryntum-suite-new-engine/SchedulerPro/lib/Core/widget/Widget.js:3655:29)
                //     at Tooltip.afterShowByTarget (http://local/Bryntum/bryntum-suite-new-engine/SchedulerPro/lib/Core/widget/Tooltip.js:744:16)
                //     at Tooltip.handleForElementOver (http://local/Bryntum/bryntum-suite-new-engine/SchedulerPro/lib/Core/widget/Tooltip.js:576:20)
                //     at Tooltip.internalOnPointerOver (http://local/Bryntum/bryntum-suite-new-engine/SchedulerPro/lib/Core/widget/Tooltip.js:474:16)
                //     at HTMLDivElement.handler (http://local/Bryntum/bryntum-suite-new-engine/SchedulerPro/lib/Core/helper/EventHelper.js:534:78)
                //
                // So we remove it from the parent first, then append to fragment.
                // The whole process of this moving elements around is not clear, should be reviewed by someone
                // who is in this context.
                // keeping #7091 opened
                followingEl.remove();

                widgetsFrag.appendChild(followingEl);
            }
        }
```

**Comment by isglass** [comment]
https://forum.bryntum.com/viewtopic.php?f=44&t=25654&p=127608#p127608
