### ISSUE TITLE
ExternalEventResource drag drop crashes if no resource on DayResourceView

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#7106]
[Forum post](https://forum.bryntum.com/viewtopic.php?p=126886#p126886)

I just got our code updated and we use an ExternalEventResource to drag onto a calendar with out a pre-assigned resource.  Version 4.5 fixed the error for all views except the new view you just added for the DayResourceView.  Here's the error I get now:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'id')
at ResourceCalendarRowZone.updateDays (calendar.module.js:151423:148)
at ResourceCalendarRowZone.set (calendar.module.js:1597:52)
at ResourceCalendarRowZone.setEventData (calendar.module.js:151055:13)
at ResourceCalendarRowZone.setupEvent (calendar.module.js:150835:8)
at ResourceCalendarRowZone.setupEvent (calendar.module.js:151394:18)
at ResourceCalendarRowZone.startMove (calendar.module.js:150876:8)
at ResourceCalendarRowZone.dragEnter (calendar.module.js:150484:10)
at ResourceCalendarRowZone.dragEnter (calendar.module.js:151005:18)
at ResourceCalendarRowZone.changeDropping (calendar.module.js:53406:16)
at ResourceCalendarRowZone.set (calendar.module.js:1588:44)
```

**Comment by matsbryntse** [comment]
test added in 7106-dragdrop
