### ISSUE TITLE
ResizeObserver loop completed with undelivered notifications

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#7373]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=25998&p=129668#p129668)
"
I've successfully replicated the issue with ResizeObserver. I attempted to disable eventResizeFeature using the following configuration:
```
eventResizeFeature: {
    disabled: true
},
```
Even disabled the `"b-sch-event-resizable-true"` class name is still present on the event, indicating that this feature remains enabled. To resolve this, you can set the property to false like this:
```
eventResizeFeature: false,
```

When set to false, the CSS property associated with resizing won't be present, and the library won't produce any resizing errors. This issue can be observed in the project located at `"\schedulerpro-5.5.0\examples-scheduler\frameworks\react\typescript\drag-from-grid\src\containers."` In my company's project, we're using version 5.5.1, and this fix also works there.
"

The feature is disabled but the class is still present, which triggers the error.

**Comment by azabraao** [comment]
When is this bugfix coming?

**Comment by dmlarionov** [comment]
I believe i'm also affected and waiting for a bugfix.

**Comment by ExtAnimal** [comment]
How is this error produced? Exactly what steps and on what browser and on what platform? Because I cannot make the error happen.

**Comment by dmlarionov** [comment]
To reproduce my case:

1. Clone https://github.com/dmlarionov/bryntum-gantt-experiment
2. `npm install` and then `npm start`
3. Open http://localhost:3000/
4. On the first tab (which contains BryntumGantt) do any of the following:
  - move separator between grid and digram
  - resize a column
  - show / hide any column then rezise it
5. Alternatively you can swith to another tab (the second tab contains BryntumResourceHistogram).

While doing any of the actions 4 or 5 you should immediately get uncaught runtime error like:

ResizeObserver loop completed with undelivered notifications.
    at handleError (http://localhost:3000/static/js/bundle.js:260064:58)
    at http://localhost:3000/static/js/bundle.js:260083:7

My environment is the following:

- Apple M1 Pro
- MacOS 14.2.1 (Sonoma)
- Chrome 120.0.6099.234 (Official Build) (arm64)
- npm version 10.2.4
- node version v20.11.0

Also checked with Firefox (121.0.1 (64-bit)), the same error.

My case isn't minimal and perhaps the error isn't rooted in the Bryntum bug, I admit. But seems it is rooted there.

**Comment by matsbryntse** [comment]
@dmlarionov Can you still repro in v6.0+?

**Comment by 0utplay** [comment]
Hi @matsbryntse I can still reproduce in 6.0.5. I will create a new forum post related to this

**Comment by isglass** [comment]
Also reported here https://forum.bryntum.com/viewtopic.php?p=154797#p154797, with failing test-case (collapse region in the demo)

**Comment by ghulamghousdev** [comment]
Another report here: https://forum.bryntum.com/viewtopic.php?p=161916#p161916
Issue is reproducible when resizing the resources column in this demo: https://bryntum.com/products/schedulerpro/examples/frameworks/react-vite/basic-thin/dist/

**Comment by ghulamghousdev** [comment]
Another report by the same user who reported [this](https://github.com/bryntum/support/issues/7373#issuecomment-2621657186) : https://forum.bryntum.com/viewtopic.php?p=161914#p161914

**Comment by alex20044** [comment]
We are also facing this issue on 6.1.5. Please prioritize fixing it.

**Comment by ghulamghousdev** [comment]
Another report here: https://forum.bryntum.com/viewtopic.php?p=162453#p162453

**Comment by marciogurka** [comment]
Another issue when using regionResize with React - https://github.com/bryntum/support/issues/10817

**Comment by NicklasHelton** [comment]
I'm experiencing this same issue on a gantt chart. Very similar to #10817

**Comment by matsbryntse** [comment]
@NicklasHelton What version are you running?

**Comment by matsbryntse** [comment]
@NicklasHelton with React?
