### ISSUE TITLE
grid: aria always assumes a parent which results in console error if not present

### ISSUE THREAD

**Issue by lubber-de** [bryntum/support#7815]
## Description
We had a looping console error when using the grid from inside the schedulerpro component

```terminal
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'children')
    at Row.render (Row.js:650:53)
    at RowManager.renderFromRow (RowManager.js:1131:17)
    at RowManager.reinitialize (RowManager.js:189:12)
    at UnplannedGrid.renderRows (GridBase.js:3342:23)
    at functionChainRunner (InstancePlugin.js:430:31)
    at plugInto.<computed> [as renderRows] (InstancePlugin.js:394:49)
    at UnplannedGrid.onStoreDataChange (GridBase.js:1981:16)
    at EventStore.trigger (Events.js:1521:44)
    at EventStore.trigger (AbstractPartOfProjectStoreMixin.js:52:36)
    at EventStore.trigger (EventStoreMixin.js:952:22)
```

### Where?
`schedulerpro/lib/Grid/Row/Row.js` Line 650
```javascript
                DomHelper.setAttributes(el, {
                    'aria-level'    : record.childLevel + 1,
                    'aria-setsize'  : record.parent.children.length, // <-- here
                    'aria-posinset' : record.parentIndex + 1
                });
```

### Possible Fix (how we did it locally)

```javascript
                DomHelper.setAttributes(el, {
                    'aria-level'    : (record.childLevel || 0) + 1,
                    'aria-setsize'  : record.parent && record.parent.children ? record.parent.children.length : 0,
                    'aria-posinset' : (record.parentIndex || 0) + 1
                });
```
## Version
5.6.0

**Comment by matsbryntse** [comment]
Thanks for reporting! How do we reproduce this?

**Comment by matsbryntse** [comment]
Not able to repro. Can you please upload a fully runnable (minimal) test case with instructions on how to reproduce?
