### ISSUE TITLE
[REACT] Gantt crashes in RTL container

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#8289]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=27626&p=138341#p138341)

Hi Support team,

we were upgrading from v5.5.5 to v5.6.5 and came across this issue.
Gannt crashes when rendered in a element with style 
```
direction:'rtl'
```
with error:

```
TypeError: me.currentOrientation.clearAll is not a function
    at Gantt.updateRtl (gantt.module.js:32855:933)
    at Gantt.set (gantt.module.js:1523:906)
    at Gantt.render (gantt.module.js:12873:520)
    at Gantt.render (gantt.module.js:13902:956)
    at Gantt.render (gantt.module.js:15014:361)
    at Gantt.render (gantt.module.js:30678:1714)
    at Gantt.render (gantt.module.js:32822:1279)
    at functionChainRunner (gantt.module.js:5968:216)
    at plugInto.<computed> [as render] (gantt.module.js:5961:921)
    at Gantt.finalizeInit (gantt.module.js:13777:364)
    at Gantt.finalizeInit (gantt.module.js:6352:211)
    at Gantt.finalizeInit (gantt.module.js:29626:817)
    at Gantt.finalizeInit (gantt.module.js:30354:1035)
    at Gantt.construct (gantt.module.js:13773:1097)
    at Gantt.construct (gantt.module.js:29289:272)
    at Gantt.construct (gantt.module.js:31943:119)
    at Gantt.construct (gantt.module.js:32207:109)
    at Gantt.construct (gantt.module.js:32676:103)
    at Gantt.construct (gantt.module.js:38584:145)
    at Gantt.construct (gantt.module.js:38601:215)
    at Gantt.construct (gantt.module.js:53153:1436)
    at new _Base (gantt.module.js:1889:93)
```

I could repro this with your react-ts basic example by replacing the content of App.tsx with following

```
/**
 * Main Application script
 */
import React, { FunctionComponent } from 'react';

import { BryntumDemoHeader, BryntumGantt } from '@bryntum/gantt-react';
import { ganttConfig } from './AppConfig';
import './App.scss';

const App: FunctionComponent = () => {
	return (
		<div style={{ direction: 'rtl', height: '100%' }}>
			{/* BryntumDemoHeader component is used for Bryntum example styling only and can be removed */}
			<BryntumDemoHeader />
			<BryntumGantt {...ganttConfig} />
		</div>
	);
};

export default App;

```

Note: in v5.5.5 we don't have this issue.

Thanks for your support!

best regards,
Xianer

**Comment by matsbryntse** [comment]
Tests + initial fix for crash in `8289-rtl`
