### ISSUE TITLE
[LWC] Exception when opening task editor on a page with Gantt and SchedulerPro LWC

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#8400]
> Disabling LWS revealed an issue with several instances of LWC on the same page. Doublib clicking in scheduler pro and gantt opens a task editor in the top left corner with the following exception in console:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'defaultView')
    at DomHelper.getVisibleViewport (gantt.lwc.module.js:66239:48)
    at DomHelper.getViewportIntersection (gantt.lwc.module.js:14899:36)
    at DomHelper.isInView (gantt.lwc.module.js:14881:29)
    at SchedulerTaskEditor.alignTo (gantt.lwc.module.js:47448:184)
    at SchedulerTaskEditor.afterShow (gantt.lwc.module.js:49056:16)
    at eval (gantt.lwc.module.js:48985:16)
    at new Promise (<anonymous>)
    at SchedulerTaskEditor.show (gantt.lwc.module.js:48906:18)
    at SchedulerTaskEditor.showBy (gantt.lwc.module.js:49019:21)
    at TaskEdit$1.editEvent (gantt.lwc.module.js:225615:30)
```

**Comment by amurashincertinia** [comment]
There might be a quick fix for this, just add some optional chaining to the `DomHelper.getVisibleViewport` method:

```js
static getVisibleViewport(startElement, docRect, targetEl) {
  const viewports = [];
  let result = docRect;

  for (let viewport = startElement; viewport && viewport !== doc.body; viewport = getParent(viewport)) {
    const style = viewport?.ownerDocument?.defaultView?.getComputedStyle(viewport);

    if ((scrollStyles[style?.overflowX] || scrollStyles[style?.overflowY]) && style?.display !== "contents") {
      viewports.unshift(Rectangle.client(viewport, null, true, true, targetEl));
    }
  }

  for (let i = 0, { length } = viewports; result && i < length; i++) {
    result = result.intersect(viewports[i]);
  }

  return result;
}
```

**Comment by JockeLindberg** [comment]
Fixed here https://github.com/bryntum/support/issues/8652
