### ISSUE TITLE
Crash when drag creating in event-items demo

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#8455]
```
DomHelper.js:1252 Uncaught TypeError: config.children.forEach is not a function
    at DomHelper.createElement (DomHelper.js:1252:29)
    at DomHelper.js:1274:47
    at Array.forEach (<anonymous>)
    at DomHelper.createElement (DomHelper.js:1252:29)
    at DomHelper.js:1274:47
    at Array.forEach (<anonymous>)
    at DomHelper.createElement (DomHelper.js:1252:29)
    at DomHelper.js:1274:47
    at Array.forEach (<anonymous>)
    at DomHelper.createElement (DomHelper.js:1252:29)
```

**Comment by matsbryntse** [comment]
Also check to make sure event-items demo renders correctly (no name currently in all-day header)
<img width="1476" alt="Screenshot 2024-02-03 at 13 23 27" src="https://github.com/bryntum/support/assets/218570/aedec95b-ea4b-485b-8c02-cef4926f5739">
