### ISSUE TITLE
Crash when advanced demo opens code editor 

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#8611]
Related to toolbar overflow handling.

http://lh/bryntum-suite/gantt/examples/advanced/?code=1
```

Identifier.js:279 Uncaught (in promise) Error: Unknown identifier ModelClass-general.$.version
    at throwUnknownIdentifier (Identifier.js:279:63)
    at EngineTransaction.onReadIdentifier (Transaction.js:626:17)
    at EngineTransaction.calculateTransitionsStackGen (Transaction.js:770:57)
    at calculateTransitionsStackGen.next (<anonymous>)
    at EngineTransaction.calculateTransitions (Transaction.js:669:25)
    at calculateTransitions.next (<anonymous>)
    at runGeneratorAsyncWithEffect (Calculation.js:151:29)
    at Transaction.js:526:20

```

**Comment by matsbryntse** [comment]
Test in `8611-crash`
