### ISSUE TITLE
Crash when pressing X button in event editor

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#8635]
http://lh/bryntum-suite/scheduler/examples/custom-event-rendering/
```
EventEdit.js:1436 Uncaught (in promise) Error: Method cannot be called at this state!
    at throwInvalidMethodCall (StateBase.js:11:11)
    at ReadyStateClass.onStopTransaction (ReadyState.js:117:9)
    at stateTransition (StateTrackingManager.js:89:26)
    at StateTrackingManager.stopTransaction (StateTrackingManager.js:581:9)
    at EventEdit.rejectStmTransaction (TaskEditStm.js:108:21)
    at EventEdit.freeStm (TaskEditStm.js:143:26)
    at EventEdit.resetEditingContext (EventEdit.js:1431:22)
    at EventEdit.onBeforeEditorToggleReveal (EventEdit.js:1417:68)
    at EventEditor.trigger (Events.js:1535:44)
    at PanelCollapserOverlay.toggleReveal (PanelCollapserOverlay.js:374:51)
```

**Comment by canonic-epicure** [comment]
Steps to reproduce:
- open event editor
- close it with the close button in its right-top corner
