### ISSUE TITLE
Scheduler Pro - error removing partner

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#8647]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=28074&p=141026#p141026)

Reproducible here with `schedulerpro/examples/resourcehistogram/`
Add this to that demo
```javascript
const utilization = window.utilization = new ResourceUtilization({
    project,
    hideHeaders       : true,
    partner           : scheduler,
    appendTo          : 'container',
    rowHeight         : 60,
    minHeight         : '10em',
    flex              : '1 1 50%',
    showBarTip        : true,
    resourceImagePath : '../_shared/images/users/',
    columns           : [
        { type : 'resourceInfo', text : 'Name', field : 'name', flex : 1, showEventCount : false }
    ]
});
```
In the console run these
```
$ schedulerPro.destroy();
$ histogram.destroy();
$ utilization.destroy();
```
And this is the callStack
```
GridScroller.js:64 Uncaught TypeError: Cannot read properties of undefined (reading 'xScrollers')
    at GridScroller.js:64:54
    at Array.forEach (<anonymous>)
    at GridScroller.removePartner (GridScroller.js:62:25)
    at ResourceUtilization.removePartner (TimelineBase.js:986:27)
    at TimelineBase.js:605:20
    at Array.forEach (<anonymous>)
    at Collection.forEach (Collection.js:374:83)
    at ResourceUtilization.doDestroy (TimelineBase.js:604:27)
    at ResourceUtilization.doDestroy [as $oldDestructor] (ProjectConsumer.js:359:15)
    at Object.destructorInterceptor (Events.js:1152:23)
```

![image](https://github.com/bryntum/support/assets/75997756/b8b70066-459f-40af-9eca-c5b1bf671159)

**Comment by matsbryntse** [comment]
test cov pushed to `8647-partner`

**Comment by pwmather** [comment]
What release do you think the fix will be included in? 5.6.x or will this be 6.0.x ? thanks

**Comment by pwmather** [comment]
Hi @matsbryntse  - just checking if there is a known milestone / version for this fix so that we can plan according? Many thanks.

**Comment by matsbryntse** [comment]
Will be part of 5.6.8. Likely out next week!

**Comment by pwmather** [comment]
Awesome - thank you
