### ISSUE TITLE
TreeGroup ID collision when multiple groups are applied and column with array data is at the top

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#8725]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=28210&p=141822#p141822)

Reproducible with Gantt basic demo

Replace the `launch-saas.json` with the data from the file below
### [launch-saas.json](https://github.com/bryntum/support/files/14477022/launch-saas.json)

And use this code inside of the gantt basic demo `app.module.js`
```javascript

import { Splitter, WidgetHelper, Gantt, SchedulerPro, ProjectModel, AvatarRendering } from '../../build/gantt.module.js';
import shared from '../_shared/shared.module.js';

// Project that will be shared by Gantt & SchedulerPro
const project = window.project = new ProjectModel({
    startDate : '2019-01-16',
    endDate   : '2019-02-13',

    // General calendar is used by default
    calendar : 'general',

    transport : {
        load : {
            url : '../_datasets/launch-saas.json'
        }
    },
    autoLoad : true,

    // This config enables response validation and dumping of found errors to the browser console.
    // It's meant to be used as a development stage helper only so please set it to false for production systems.
    validateResponse : true
});

const gantt = new Gantt({
    project,

    tbar : [
        {
            type : 'widget',
            html : 'Zoom:'
        },
        {
            ref      : 'zoomInButton',
            icon     : 'b-icon-search-plus',
            tooltip  : 'Zoom in',
            onAction : () => gantt.zoomIn()
        },
        {
            ref      : 'zoomOutButton',
            icon     : 'b-icon-search-minus',
            tooltip  : 'Zoom out',
            onAction : () => gantt.zoomOut()
        }
    ],

    resourceImageFolderPath : '../_shared/images/users/',
    appendTo                : 'container',
    flex                    : 1,
    features                : {
        labels : {
            left : {
                field  : 'name',
                editor : {
                    type : 'textfield'
                }
            }
        }
    },

    viewPreset  : 'weekAndDayLetter',
    columnLines : true,

    columns : [
        { type : 'sequence', minWidth : 50, width : 50, text : '', align : 'right', resizable : false },
        { type : 'name', width : 280 },
        { type : 'percent', text : '% Completed', field : 'percentDone', showValue : false, width : 160 },
        { type : 'resourceassignment', text : 'Assigned Resources', showAvatars : true, width : 160 }
    ],

    startDate : '2019-01-11',

    listeners : {
        beforeCellEditStart : ({ editorContext }) => editorContext.column.field !== 'percentDone' || editorContext.record.isLeaf
    }
});

new Splitter({
    appendTo : 'container'
});

const scheduler = new SchedulerPro({
    project,

    appendTo            : 'container',
    minHeight           : '20em',
    flex                : 1,
    partner             : gantt,
    rowHeight           : 45,
    eventColor          : 'gantt-green',
    useInitialAnimation : false,

    resourceImagePath : '../_shared/images/users/',

    features : {
        dependencies : true,
        percentBar   : true,
        tree: true,
        treeGroup: true,
    },

    columns : [
        {
            type           : 'tree',
            field          : 'name',
            text           : 'Resource',
            showEventCount : false,
            width          : 330,
            renderer({
                         record,
                         grid,
                         value,
                     }) {
                if (record .children) {
                    return record.key;
                }

                const resource = record;

                const avatarRendering = new AvatarRendering({
                    element: grid.element,
                });

                return {
                    children: [
                        avatarRendering.getResourceAvatar({
                            initials: resource.initials,
                            iconCls: resource.iconCls,
                        }),
                        value,
                    ],
                };
            },
        },
        {
            text     : 'Assigned tasks',
            field    : 'events.length',
            width    : 160,
            editor   : false,
            align    : 'right',
            renderer : ({ value }) => `${value} task${value !== 1 ? 's' : ''}`
        },
        {
            text     : 'Assigned work days',
            width    : 160,
            editor   : false,
            align    : 'right',
            renderer : ({ record }) => record.events.map(task => task.duration).reduce((total, current) => {
                return total + current;
            }, 0) + ' days'
        },
        {
            text: "Group",
            width: 160,
            field: "group",
        },
        {
            text: "Skills",
            width: 160,
            field: "skills",
        },
    ]
});
```

And then inside the console run these code
```javascript
> schedulerPro.group(["group", "skills"])
> schedulerPro.group(["skills", "group"])
```

Now you'd see this error
```
Store.js:1651  Uncaught (in promise) Error: Id collision on generated_skill_2_Group_1_
    at ResourceStore3.register (Store.js:1651:23)
    at ResourceStore3.register (ChronoPartOfProjectStoreMixin.js:31:33)
    at ModelClass.joinStore (Model.js:2716:19)
    at ModelClass.joinStore (AbstractPartOfProjectModelMixin.js:27:34)
    at Model.js:2726:71
    at Array.forEach (<anonymous>)
    at ModelClass.joinStore (Model.js:2726:48)
    at ModelClass.joinStore (AbstractPartOfProjectModelMixin.js:27:34)
    at TreeNode.js:817:32
    at Array.forEach (<anonymous>)
```

**Comment by canonic-epicure** [comment]
This issue is actually reproducible in the plain grid:
```js
import '../_shared/shared.js'; // not required, our example styling etc.
import '../../lib/Gantt/feature/Labels.js';
import '../../lib/Gantt/column/AllColumns.js';
import '../../lib/Grid/feature/TreeGroup.js';
import Grid from '../../lib/Grid/view/Grid.js';
import ProjectModel from '../../lib/Gantt/model/ProjectModel.js';

// Project that will be shared by Gantt & SchedulerPro
const project = window.project = new ProjectModel({
    startDate : '2019-01-16',
    endDate   : '2019-02-13',

    transport : {
        load : {
            url : '../_datasets/launch-saas.json'
        }
    },
    autoLoad : true
});

const grid = new Grid({
    store : project.resourceStore,

    appendTo : 'container',

    features : {
        tree      : true,
        treeGroup : true
    },

    columns : [
        {
            type  : 'tree',
            field : 'name',
            text  : 'Resource',
            width : 330
        },
        {
            text  : 'Group',
            width : 160,
            field : 'group'
        },
        {
            text  : 'Skills',
            width : 160,
            field : 'skills'
        }
    ]
});
```

**Comment by canonic-epicure** [comment]
And it seems the cause of the bug are the array values of the "skills" field - works fine when its a scalar value. Test case created "Should not throw when grouping on the array field" in `Grid/tests/features/TreeGroup.t.js`
