### ISSUE TITLE
Exception adding new task above a task with invalid field value

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#8732]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=28208&p=141830#p141830)

Hi,

I get the following exception when adding a new task above a task with an invalid value within a column cell:
DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

Reproducible with the Gantt advanced demo http://lh/bryntum-suite/gantt/examples/advanced/

Steps to reproduce in advanced example for 5.6.7:

1. Set start date field to required
2. Double click in the start date column cell of a task and delete the date value
3. Do a right click to open the task context menu
4. Add a new task above

Here is a video of reproduction

https://github.com/bryntum/support/assets/75997756/fc9ace15-569e-4f64-a20c-d8f35f72048a

CallStack : 
```
Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at Menu.toFront (http://lh/bryntum-suite/gantt/lib/Core/widget/Widget.js:3734:20)
    at Menu.onFocusIn (http://lh/bryntum-suite/gantt/lib/Core/widget/Widget.js:6014:16)
    at Menu.onFocusIn (http://lh/bryntum-suite/gantt/lib/Core/widget/Popup.js:409:15)
    at focusin (http://lh/bryntum-suite/gantt/lib/Core/GlobalEvents.js:363:51)
    at HTMLBodyElement.handler (http://lh/bryntum-suite/gantt/lib/Core/helper/EventHelper.js:544:78)
```

**Comment by matsbryntse-dev** [comment]
<details>
<summary>Video Analysis (automated)</summary>

## Video Analysis: DOMException thrown when adding a task above a row with an invalid (empty) start date

**Source:** Issue body
**Duration:** 44.8s | **Frames analyzed:** 44

### Initial State

The Bryntum Gantt **Advanced demo** is open (`gantt/examples/advanced/`). A split-pane layout is visible: the Gantt chart occupies the left two-thirds of the screen and a **Code editor** panel is open on the right. The Gantt shows a multi-level task hierarchy (rows numbered 1–1.2.2) with a timeline spanning several months. The browser DevTools Console panel is also visible at the far right, showing a version-mismatch warning but no errors yet.

### Reproduction Steps

1. **Open the Code editor and set the `startDate` field to `required: true`** (frames 3–22, ~2–22s)

   The user opens the built-in Code editor panel (right side). They scroll through the configuration source and locate the `columns` definition. Inside the column configuration for the `startDate` column they add (or confirm) `required: true` — visible as a highlighted property in the editor. After editing, the user clicks the **Apply** button in the code editor toolbar to reload the Gantt with the new configuration.

2. **Gantt reloads with the updated configuration** (frames 23–27, ~23–27s)

   The code editor panel closes and the Gantt refreshes. The task grid and chart bars render normally. The `startDate` column is now marked as required (a "This field is required" tooltip will appear on empty values).

3. **Double-click the Start Date cell of the "Install apache" task (row 2.2) to open the inline editor** (frames 28–30, ~28–30s)

   The user double-clicks the `Start` column cell for the task labelled **"Install apache"** (row 2.2). The cell enters edit mode, revealing a date picker input field with the existing date value selected.

4. **Delete the entire date value, leaving the cell empty** (frames 30–31, ~30–31s)

   The user clears the date field content completely. The cell now shows an empty input. A red validation tooltip appears reading **"This field is required"**, confirming the `required: true` constraint is active. The Gantt cell remains in edit mode with the invalid (empty) value.

5. **Right-click the same task row to open the context menu** (frames 32–33, ~32–33s)

   Without committing or cancelling the inline edit, the user right-clicks on the **"Install apache"** task row. A context menu appears with top-level items: **Edit task**, **Convert to milestone**, **Add**, **Outdent**, **Successor**, **Delete**.

6. **Hover over "Add" to expand the submenu** (frames 34–35, ~34–35s)

   The user moves the cursor over the **Add** menu item. A submenu expands to the right showing: **Task above**, **Task below**, **Subtask**, **Predecessor**, **Successor**.

7. **Click "Task above"** (frames 37–38, ~37–38s)

   The user clicks the **Task above** option. The context menu closes.

8. **DOMException is thrown immediately** (frame 39, ~39s)

   The moment "Task above" is actioned, the DevTools Console displays a red uncaught exception:

   ```
   Uncaught DOMException: Failed to execute 'insertBefore' on 'Node':
   The node before which the new node is to be inserted is not a child of this node.
       at Menu.toFront (Widget.js:3734)
       at Menu.onFocusIn (Widget.js:6014)
       at Menu.onFocusIn (Popup.js:409)
       at focusin (GlobalEvents.js:363)
       at HTMLBodyElement.handler (EventHelper.js:544)
   ```

   The error fires inside `Menu.toFront()`, triggered by a `focusin` event. The menu tries to move itself to the front of the DOM by calling `insertBefore`, but the reference node it holds is no longer a child of the expected parent — because the inline editor's DOM node was detached or re-parented when the new task row was inserted above.

9. **Gantt enters a broken state** (frames 40–44, ~40–44s)

   After the exception, the Gantt grid appears partially broken. The task row "Install apache" is highlighted but the Gantt is no longer fully interactive. The console continues to show the error. No new task row is visibly inserted above "Install apache". The context menu is dismissed. The inline editor is gone, but the empty start date value persists for the original task.

### Observed Result

Clicking **Add > Task above** (or any "Add" submenu item) while a cell inline editor is open with an invalid/empty required field throws:

```
DOMException: Failed to execute 'insertBefore' on 'Node':
The node before which the new node is to be inserted is not a child of this node.
```

The exception originates in `Menu.toFront()` called from `onFocusIn`, indicating the menu's internal DOM reference becomes stale when row insertion causes the grid to re-render, detaching the node the menu still holds a reference to.

### Expected Result

One of the following should happen gracefully:

- The context menu action should be blocked while an invalid inline editor is active, with a user-facing validation message, **or**
- The inline editor should be cancelled or committed cleanly before the row insertion proceeds, so that `Menu.toFront` operates on a valid, still-attached DOM node.

No unhandled `DOMException` should be thrown in either case.

### Key Observations

- **Product:** Bryntum Gantt
- **Version:** 5.6.7 (confirmed in the console warning visible throughout the video)
- **Demo:** `gantt/examples/advanced/`
- **Affected features:** `CellEditing` (inline editor), `TaskContextMenu` (Add > Task above), `required` field validation
- **Trigger condition:** A cell must be in edit mode with a `required` field left empty, and the user must open the context menu on the same row and select any "Add" submenu item
- **Root cause hint:** `Menu.toFront()` calls `insertBefore` with a stale DOM node reference. The reference goes stale because inserting a task row above triggers a grid re-render that detaches the current row's DOM element, but the Menu widget still holds the old node reference
- **Stack trace entry point:** `GlobalEvents.js` focusin handler → `Popup.onFocusIn` → `Widget.onFocusIn` → `Widget.toFront`

</details>
