### ISSUE TITLE
Cannot open event's Task editor in Schedular Pro

### ISSUE THREAD

**Issue by salmanthasleem** [bryntum/support#8831]
Following code removes all columns from the predecessor and successor tabs and then adds custom columns in the beforeTaskEditShow,
```
beforeTaskEditShow({ editor }) {
					const
						successorsGrid = editor.widgetMap.successorsTab.grid,
						predecessorsGrid = editor.widgetMap.predecessorsTab.grid;

					successorsGrid.columns.removeAll();
					predecessorsGrid.columns.removeAll();
                                        successorsGrid.columns.add(customColumns("successor"));
					predecessorsGrid.columns.add(customColumns("predecessor"));

}
```
When trying open up the task editor for an event after closing the currently opened task editor,
the following is error is thrown,
```
DependencyTab.js:301  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'store')
    at PredecessorsTab.loadEvent (DependencyTab.js:301:11)
    at TaskEditorBase.js:300:19
    at TabPanel.eachWidget (Widget.js:4858:9)
    at SchedulerTaskEditor.eachWidget (Widget.js:4863:1)
    at SchedulerTaskEditor.callWidgetHook (TaskEditorBase.js:297:9)
    at SchedulerTaskEditor.loadEvent (TaskEditorBase.js:278:12)
    at TaskEdit.load (TaskEdit.js:913:13)
    at TaskEdit.editEvent (TaskEdit.js:781:34)
loadEvent @ DependencyTab.js:301
(anonymous) @ TaskEditorBase.js:300
eachWidget @ Widget.js:4858
eachWidget @ Widget.js:4863
callWidgetHook @ TaskEditorBase.js:297
loadEvent @ TaskEditorBase.js:278
load @ TaskEdit.js:913
editEvent @ TaskEdit.js:781
await in editEvent (async)
onActivateEditor @ TaskEdit.js:689
trigger @ Events.js:1339
handleScheduleEvent @ TimelineDomEvents.js:186
handler @ EventHelper.js:486

```

**Comment by matsbryntse** [comment]
Please post support related questions here: https://forum.bryntum.com/

This issues repo is for confirmed bugs and feature requests only.
