### ISSUE TITLE
Gantt ASPNET frontend example not building

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#8978]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=28530&p=144231#p144231)

"Hi,

I am trying to build aspnet/aspnetcore projects from examples. Using version gantt-5.6.8.
I have followed steps from ReadMe. 
Got the following error at stage "npm run build". 
Any pointers please to resolve the issue?

```
> aspnetcore@5.6.8 build C:\temp\bryntum-gantt-5.6.8\gantt-5.6.8\examples\frameworks\aspnetcore\BryntumGanttDemo\wwwroot\app
webpack --config webpack.config.js

Hash: a03bac160422bc055640ec73af865d56e60bd6cb
Version: webpack 4.41.6
Child
    Hash: a03bac160422bc055640
    Time: 1479ms
    Built at: 28/03/2024 09:10:20
     1 asset
    Entrypoint cruddemo = cruddemo.js
    [0] ./app.js 5.98 KiB {0} [built] [failed] [1 error]
    
WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/

ERROR in ./app.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] C:\temp\bryntum-gantt-5.6.8\gantt-5.6.8\examples\frameworks\aspnetcore\BryntumGanttDemo\wwwroot\app\app.js: Could not find plugin "transform-unicode-sets-regex". Ensure there is an entry in ./available-plugins.js for it. (While processing: "C:\\temp\\bryntum-gantt-5.6.8\\\gantt-5.6.8\\examples\\frameworks\\aspnetcore\\BryntumGanttDemo\\wwwroot\\app\\node_modules\\@babel\\preset-env\\lib\\index.js")
    at getPlugin (C:\temp\bryntum-gantt-5.6.8\gantt-5.6.8\examples\frameworks\aspnetcore\BryntumGanttDemo\wwwroot\app\node_modules\@babel\preset-env\lib\index.js:67:11)
    at C:\temp\bryntum-gantt-5.6.8\gantt-5.6.8\examples\frameworks\aspnetcore\BryntumGanttDemo\wwwroot\app\node_modules\@babel\preset-env\lib\index.js:258:62
    at Array.map (<anonymous>)
```

Thanks"

- If you use Node 18, and try to build the `"@bryntum/gantt": "6.0.0-alpha-2"` version located at `Gantt/examples/frameworks/aspnet/BryntumGanttCrudDemo/app`, it triggers an error
```
npm run build

> aspnet@5.6.9 build
> webpack --config webpack.config.js --progress

Hash: e4208ee3441ef85ada32cc4aceff919e0c4cab46
Version: webpack 4.41.6
Child
    Hash: e4208ee3441ef85ada32
    Time: 453ms
    Built at: 04/10/2024 9:35:22 AM
     1 asset
    Entrypoint cruddemo = cruddemo.js
    [0] ./app.js 5.33 KiB {0} [built] [failed] [1 error]
    
    WARNING in configuration
    The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
    You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/
    
    ERROR in ./app.js
    Module build failed (from ./node_modules/babel-loader/lib/index.js):
    Error: [BABEL] /Users/marciogurka/Developer/Sites/bryntum-suite/Gantt/examples/frameworks/aspnet/BryntumGanttCrudDemo/app/app.js: Could not find plugin "transform-unicode-sets-regex". Ensure there is an entry in ./available-plugins.js for it. (While processing: "/Users/marciogurka/Developer/Sites/bryntum-suite/Gantt/examples/frameworks/aspnet/BryntumGanttCrudDemo/app/node_modules/@babel/preset-env/lib/index.js")
        at getPlugin (/Users/marciogurka/Developer/Sites/bryntum-suite/Gantt/examples/frameworks/aspnet/BryntumGanttCrudDemo/app/node_modules/@babel/preset-env/lib/index.js:67:11)
        at /Users/marciogurka/Developer/Sites/bryntum-suite/Gantt/examples/frameworks/aspnet/BryntumGanttCrudDemo/app/node_modules/@babel/preset-env/lib/index.js:258:62
        at Array.map (<anonymous>)
        at /Users/marciogurka/Developer/Sites/bryntum-suite/Gantt/examples/frameworks/aspnet/BryntumGanttCrudDemo/app/node_modules/@babel/preset-env/lib/index.js:258:43
        at /Users/marciogurka/Developer/Sites/bryntum-suite/Gantt/examples/frameworks/aspnet/BryntumGanttCrudDemo/app/node_modules/@babel/helper-plugin-utils/lib/index.js:33:12
        at /Users/marciogurka/Developer/Sites/bryntum-suite/Gantt/examples/frameworks/aspnet/BryntumGanttCrudDemo/app/node_modules/@babel/core/lib/config/full.js:199:14
        at Generator.next (<anonymous>)
        at Function.<anonymous> (/Users/marciogurka/Developer/Sites/bryntum-suite/Gantt/examples/frameworks/aspnet/BryntumGanttCrudDemo/app/node_modules/@babel/core/lib/gensync-utils/async.js:26:3)
        at Generator.next (<anonymous>)
        at step (/Users/marciogurka/Developer/Sites/bryntum-suite/Gantt/examples/frameworks/aspnet/BryntumGanttCrudDemo/app/node_modules/gensync/index.js:261:32)
        at evaluateAsync (/Users/marciogurka/Developer/Sites/bryntum-suite/Gantt/examples/frameworks/aspnet/BryntumGanttCrudDemo/app/node_modules/gensync/index.js:291:5)
        at Function.errback (/Users/marciogurka/Developer/Sites/bryntum-suite/Gantt/examples/frameworks/aspnet/BryntumGanttCrudDemo/app/node_modules/gensync/index.js:113:7)
        at errback (/Users/marciogurka/Developer/Sites/bryntum-suite/Gantt/examples/frameworks/aspnet/BryntumGanttCrudDemo/app/node_modules/@babel/core/lib/gensync-utils/async.js:70:18)
        at async (/Users/marciogurka/Developer/Sites/bryntum-suite/Gantt/examples/frameworks/aspnet/BryntumGanttCrudDemo/app/node_modules/gensync/index.js:188:17)
        at onFirstPause (/Users/marciogurka/Developer/Sites/bryntum-suite/Gantt/examples/frameworks/aspnet/BryntumGanttCrudDemo/app/node_modules/gensync/index.js:216:13)
        at Generator.next (<anonymous>)
        at cachedFunction (/Users/marciogurka/Developer/Sites/bryntum-suite/Gantt/examples/frameworks/aspnet/BryntumGanttCrudDemo/app/node_modules/@babel/core/lib/config/caching.js:68:46)
        at cachedFunction.next (<anonymous>)
        at loadPresetDescriptor (/Users/marciogurka/Developer/Sites/bryntum-suite/Gantt/examples/frameworks/aspnet/BryntumGanttCrudDemo/app/node_modules/@babel/core/lib/config/full.js:292:44)
        at loadPresetDescriptor.next (<anonymous>)
        at recurseDescriptors (/Users/marciogurka/Developer/Sites/bryntum-suite/Gantt/examples/frameworks/aspnet/BryntumGanttCrudDemo/app/node_modules/@babel/core/lib/config/full.js:107:30)
        at recurseDescriptors.next (<anonymous>)
        at loadFullConfig (/Users/marciogurka/Developer/Sites/bryntum-suite/Gantt/examples/frameworks/aspnet/BryntumGanttCrudDemo/app/node_modules/@babel/core/lib/config/full.js:142:6)
        at loadFullConfig.next (<anonymous>)
        at Function.transform (/Users/marciogurka/Developer/Sites/bryntum-suite/Gantt/examples/frameworks/aspnet/BryntumGanttCrudDemo/app/node_modules/@babel/core/lib/transform.js:25:45)
        at transform.next (<anonymous>)
        at step (/Users/marciogurka/Developer/Sites/bryntum-suite/Gantt/examples/frameworks/aspnet/BryntumGanttCrudDemo/app/node_modules/gensync/index.js:269:25)
        at /Users/marciogurka/Developer/Sites/bryntum-suite/Gantt/examples/frameworks/aspnet/BryntumGanttCrudDemo/app/node_modules/gensync/index.js:273:13
        at async.call.result.err.err (/Users/marciogurka/Developer/Sites/bryntum-suite/Gantt/examples/frameworks/aspnet/BryntumGanttCrudDemo/app/node_modules/gensync/index.js:223:11)
        at /Users/marciogurka/Developer/Sites/bryntum-suite/Gantt/examples/frameworks/aspnet/BryntumGanttCrudDemo/app/node_modules/gensync/index.js:189:28
        at /Users/marciogurka/Developer/Sites/bryntum-suite/Gantt/examples/frameworks/aspnet/BryntumGanttCrudDemo/app/node_modules/@babel/core/lib/gensync-utils/async.js:72:7
        at /Users/marciogurka/Developer/Sites/bryntum-suite/Gantt/examples/frameworks/aspnet/BryntumGanttCrudDemo/app/node_modules/gensync/index.js:113:33
        at step (/Users/marciogurka/Developer/Sites/bryntum-suite/Gantt/examples/frameworks/aspnet/BryntumGanttCrudDemo/app/node_modules/gensync/index.js:287:14)
        at /Users/marciogurka/Developer/Sites/bryntum-suite/Gantt/examples/frameworks/aspnet/BryntumGanttCrudDemo/app/node_modules/gensync/index.js:273:13
        at async.call.result.err.err (/Users/marciogurka/Developer/Sites/bryntum-suite/Gantt/examples/frameworks/aspnet/BryntumGanttCrudDemo/app/node_modules/gensync/index.js:223:11)
        at /Users/marciogurka/Developer/Sites/bryntum-suite/Gantt/examples/frameworks/aspnet/BryntumGanttCrudDemo/app/node_modules/gensync/index.js:189:28
Child
    Hash: cc4aceff919e0c4cab46
    Time: 558ms
    Built at: 04/10/2024 9:35:23 AM
                                    Asset       Size  Chunks                    Chunk Names
                             cruddemo.css    450 KiB       0  [emitted]  [big]  main
                              favicon.png  579 bytes          [emitted]         
           fonts/bryntum-symbol-white.svg  518 bytes          [emitted]         
                   fonts/fa-solid-900.ttf    410 KiB          [emitted]  [big]  
                 fonts/fa-solid-900.woff2    153 KiB          [emitted]         
         fonts/poppins-v20-latin-100.woff   9.81 KiB          [emitted]         
        fonts/poppins-v20-latin-100.woff2   7.31 KiB          [emitted]         
         fonts/poppins-v20-latin-200.woff   10.3 KiB          [emitted]         
        fonts/poppins-v20-latin-200.woff2   7.75 KiB          [emitted]         
         fonts/poppins-v20-latin-300.woff   10.3 KiB          [emitted]         
        fonts/poppins-v20-latin-300.woff2   7.66 KiB          [emitted]         
         fonts/poppins-v20-latin-500.woff   10.1 KiB          [emitted]         
        fonts/poppins-v20-latin-500.woff2   7.57 KiB          [emitted]         
         fonts/poppins-v20-latin-600.woff   10.4 KiB          [emitted]         
        fonts/poppins-v20-latin-600.woff2   7.81 KiB          [emitted]         
         fonts/poppins-v20-latin-700.woff   10.2 KiB          [emitted]         
        fonts/poppins-v20-latin-700.woff2   7.63 KiB          [emitted]         
         fonts/poppins-v20-latin-800.woff   10.2 KiB          [emitted]         
        fonts/poppins-v20-latin-800.woff2   7.64 KiB          [emitted]         
         fonts/poppins-v20-latin-900.woff   9.95 KiB          [emitted]         
        fonts/poppins-v20-latin-900.woff2   7.45 KiB          [emitted]         
     fonts/poppins-v20-latin-regular.woff   10.3 KiB          [emitted]         
    fonts/poppins-v20-latin-regular.woff2    7.7 KiB          [emitted]         
                                      tmp   3.63 KiB       0  [emitted]         main
    Entrypoint main [big] = cruddemo.css tmp
    [0] ./resources/app.css 39 bytes {0} [built]
        + 3 hidden modules
    
    WARNING in configuration
    The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
    You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/
    
    WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
    This can impact web performance.
    Assets: 
      fonts/fa-solid-900.ttf (410 KiB)
      cruddemo.css (450 KiB)
    
    WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
    Entrypoints:
      main (454 KiB)
          cruddemo.css
          tmp
    
    
    WARNING in webpack performance recommendations: 
    You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
    For more info visit https://webpack.js.org/guides/code-splitting/
```

**Comment by marciogurka** [comment]
[+1](https://forum.bryntum.com/viewtopic.php?p=144667#p144667) for this
