### ISSUE TITLE
[REACT] Gantt React Next.js apps have broken production code for trial

### ISSUE THREAD

**Issue by SergeyMaltsev** [bryntum/support#9274]
https://bryntum.com/products/gantt/examples/frameworks/react-nextjs/app-router/

![image](https://github.com/bryntum/support/assets/57486330/9a73f953-30ba-40c2-9cce-f9cab983249c)

```
TypeError: Cannot read properties of null (reading 'removeChild')
    at e.value (rootcause-full.js?476743:10:64371)
    at e.value [as SUPER] (rootcause-full.js?476743:10:51668)
    at e.stop (rootcause-full.js?476743:10:250423)
    at e.<computed> (rootcause-full.js?476743:10:91099)
    at e.stop (rootcause-full.js?476743:10:142414)
    at e.<computed> (rootcause-full.js?476743:10:91099)
    at e.value (rootcause-full.js?476743:10:53542)
    at e.value (rootcause-full.js?476743:10:52289)
    at u (139-b048ded6b8751001.js?476743:1:66296)
    at 2443530c-9b9e48e886c3292d.js?476743:9:103021
2443530c-9b9e48e886c3292d.js?476743:9  Uncaught Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at tZ (2443530c-9b9e48e886c3292d.js?476743:9:22606)
    at iv (2443530c-9b9e48e886c3292d.js?476743:9:115340)
    at oR (2443530c-9b9e48e886c3292d.js?476743:9:90030)
    at 2443530c-9b9e48e886c3292d.js?476743:9:86288
    at 2443530c-9b9e48e886c3292d.js?476743:9:86295
    at ok (2443530c-9b9e48e886c3292d.js?476743:9:86400)
    at E (139-b048ded6b8751001.js?476743:25:1398)
    at C (139-b048ded6b8751001.js?476743:25:1951)
    at rootcause-full.js?476743:10:615668
    at o (rootcause-full.js?476743:10:615783)
```

Also in tests app code fails with right click at this place
Can be reproduced in TC Monkey tests with `setMonkeyActions([{"rightclick":[470,694]}])`

![image](https://github.com/bryntum/support/assets/57486330/077f403e-1f42-4938-abe9-be28c0d6d00e)

```
Unhandled promise rejection in test monkey-frameworks-react-nextjs-app-router-test

TypeError: Cannot read properties of undefined (reading 'result')
    at e.alignTo (https://qa2.bryntum.com/workspace/BUILDS/7483/Bryntum/bryntum-suite/Gantt/gantt-trial/examples/frameworks/react-nextjs/app-router/out/_next/static/chunks/0f2005c8-6000d8289ab77082.js:1:85266
    at cN.alignTo (https://qa2.bryntum.com/workspace/BUILDS/7483/Bryntum/bryntum-suite/Gantt/gantt-trial/examples/frameworks/react-nextjs/app-router/out/_next/static/chunks/0f2005c8-6000d8289ab77082.js:1:810259
    at cN.afterShow (https://qa2.bryntum.com/workspace/BUILDS/7483/Bryntum/bryntum-suite/Gantt/gantt-trial/examples/frameworks/react-nextjs/app-router/out/_next/static/chunks/0f2005c8-6000d8289ab77082.js:1:833935
    at cN.afterShow (https://qa2.bryntum.com/workspace/BUILDS/7483/Bryntum/bryntum-suite/Gantt/gantt-trial/examples/frameworks/react-nextjs/app-router/out/_next/static/chunks/0f2005c8-6000d8289ab77082.js:1:943149
    at cN.afterShow (https://qa2.bryntum.com/workspace/BUILDS/7483/Bryntum/bryntum-suite/Gantt/gantt-trial/examples/frameworks/react-nextjs/app-router/out/_next/static/chunks/0f2005c8-6000d8289ab77082.js:1:951204
    at https://qa2.bryntum.com/workspace/BUILDS/7483/Bryntum/bryntum-suite/Gantt/gantt-trial/examples/frameworks/react-nextjs/app-router/out/_next/static/chunks/0f2005c8-6000d8289ab77082.js:1:833253
...

```

The reason is that original API code

```
// Initial success, or axisLock. Use first successful solution.
result     = solutions[0].result;
resultZone = solutions[0].zone;
```

is finally minified in application to 

```
n = [][0].result,
a = [][0].zone
```

Which is obviously wrong.

Same test fails with `react-nextjs/pages-router/`.
But online example https://bryntum.com/products/gantt/examples/frameworks/react-nextjs/pages-router doesn't warn about  `Minified React error #418`

**Comment by SergeyMaltsev** [comment]
Not reproducible now
