### ISSUE TITLE
Gantt ProjectModel cannot be recreated

### ISSUE THREAD

**Issue by SergeyMaltsev** [bryntum/support#9289]
```
import Gantt from '../../lib/Gantt/view/Gantt.js';
import StringHelper from '../../lib/Core/helper/StringHelper.js';
import ProjectModel from '../../lib/Gantt/model/ProjectModel.js';

const calendars = [
    {
        id        : 'general',
        name      : 'General',
        intervals : [
            {
                recurrentStartDate : 'on Sat at 0:00',
                recurrentEndDate   : 'on Mon at 0:00',
                isWorking          : false
            }
        ]
    }
];

let project;

const createProject = () => {
    project = new ProjectModel({
        calendar  : 'general',
        startDate : new Date(),
        calendars
    });
};

createProject();
project.destroy();
createProject();
```

Throws

```
ObjectHelper.js:309  Uncaught TypeError: Cannot create property 'id' on boolean 'true'
    at ObjectHelper.js:309:24
    at Array.map (<anonymous>)
    at ObjectHelper.transformNamedObjectToArray (ObjectHelper.js:306:71)
    at CalendarIntervalStore.setStoreData (Store.js:1666:33)
    at CalendarIntervalStore.setStoreData (AbstractPartOfProjectStoreMixin.js:91:37)
    at set data (Store.js:1629:14)
    at StoreDataField.set (StoreDataField.js:241:24)
    at ModelClass.assignInitables (Model.js:1446:23)
    at ModelClass.construct (Model.js:927:44)
    at ModelClass.construct (ChronoModelMixin.js:30:34)
```

Related to intervals field, which is StoreField

**Comment by canonic-epicure** [comment]
Works like this:
```
const createProject = () => {
    project = new ProjectModel({
        calendar  : 'general',
        startDate : new Date(),
        calendarManagerStore : { useRawData : false },
        calendars
    });
};
```

Related to the new default value of `useRawData` (now enabled by default), so the calendars array is "consumed" by the project and turned into internal structures, but later the same object is used for loading data
