### ISSUE TITLE
Editor throws in calendar after copy paste

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#9315]
Exception thrown when opening task edit.

Steps:
1. copy and paste one event (it should be pasted with a single resource)
2. open task editor for this event, notice resource picker is a simple combo
3. open editor for events with two resources - exception is thrown

```
Uncaught (in promise) Error: Multiple values cannot be set to a non-multiSelect Combo
    at ResourceCombo.changeValue (Combo.js:1190:19)
    at ResourceCombo.set (Config.js:438:54)
    at set value (Combo.js:1168:21)
    at EventEdit.internalLoadRecord (EventEdit.js:1092:40)
    at EventEdit.loadRecord (EventEdit.js:1048:14)
    at EventEdit.internalShowEditor (EventEdit.js:742:16)
    at EventEdit.internalShowEditor (EventEdit.js:316:19)
    at EventEdit.doEditEvent (EventEdit.js:254:12)
    at EventEdit.editEvent (EventEdit.js:959:19)
    at EventEdit.onActivateEditor (EventEdit.js:1386:18)
```

Issue is not reproducible when you drag create an event, or add new event via context menu.

Related; https://github.com/bryntum/support/issues/9299

**Comment by ExtAnimal** [comment]
Doesn't happen:

<img width="730" alt="Screenshot 2024-08-11 at 07 57 54" src="https://github.com/user-attachments/assets/fa2a48c7-5d4f-4022-8540-da09bf98c926">

**Comment by bmblb** [comment]
Confirmed, cannot reproduce anymore
