### ISSUE TITLE
Exceptions when copy pasting records in grid demo with charts

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#9319]
Reproducible on `nested-grid-with-charts` demo

# Pasting records between nested grids

1. expand Doug Jones and James Davis
2. copy any record from Doug's grid and paste to James' grid, see exception:

```
TaskModel.js:16  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'rate')
    at get cost (TaskModel.js:16:30)
    at ModelClass.getValue (Model.js:1786:24)
    at NumberColumn.getRawValue (Column.js:2573:23)
    at Row.renderCell (Row.js:835:35)
    at Row.render (Row.js:747:23)
    at RowManager.renderFromRow (RowManager.js:1280:17)
    at TaskGrid.refreshFromRowOnStoreAdd (GridBase.js:1929:20)
    at TaskGrid.onStoreAdd (GridBase.js:2035:16)
    at Store.trigger (Events.js:1543:44)
    at Store.onDataChange (Store.js:1067:24)
```

# Opening a context menu

1. Open context menu for the record in the nested grid, select Copy
2. Open context menu for the record in the main grid, see exception
```
Model.js:2216  Uncaught (in promise) TypeError: Cannot set property fullName of [object Object] which has only a getter
    at ModelClass.applyValue (Model.js:2216:36)
    at ModelClass.inSet (Model.js:2170:20)
    at ModelClass.set (Model.js:1954:31)
    at RowCopyPaste.setFromStringData (CopyPasteBase.js:308:42)
    at RowCopyPaste.stringParser (RowCopyPaste.js:403:21)
    at RowCopyPaste.transformClipboardText (Clipboardable.js:362:45)
    at RowCopyPaste.hasClipboardData (Clipboardable.js:381:41)
    at RowCopyPaste.populateCellMenu (RowCopyPaste.js:488:38)
    at functionChainRunner (InstancePlugin.js:455:31)
    at plugInto.<computed> [as populateCellMenu] (InstancePlugin.js:419:49)
```

**Comment by matsbryntse** [comment]
Also, 2 first rows report 0 as total
<img width="1920" alt="Screenshot 2024-06-06 at 08 41 11" src="https://github.com/bryntum/support/assets/218570/e64df75b-dda3-4e5a-801f-cefc7be556f4">
