### ISSUE TITLE
[SALESFORCE] Objects.isObject() returns True for Event and Element instances in Locker

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#9500]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=29588&p=149601#p149601)

Hello there!

We have recently discovered a bug that is only occurring in limited circumstances. The bug was first discovered in 5.6.11 but it may have originated earlier. It is still reproducible in 5.6.13 (we are not on v6 yet).

When Lightning Web Security is switched OFF, right-clicking on a task card in the TaskBoard will display the context menu incorrectly aligned (in the top left corner), and an error is thrown in the browser console:

```
RangeError: Maximum call stack size exceeded
    at Object.hasOwn (<anonymous>)
    at Function.hasOwn (<anonymous>)
    at getPropertyOwner (all.lwc.js:76029:18)
    at Object.get (all.lwc.js:76043:25)
    at Objects.isObject (all.lwc.js:1570:50)
    at Objects.isObject (all.lwc.js:76166:68)
    at Objects.clone (all.lwc.js:1425:23)
    at Objects.clone (all.lwc.js:1431:39)
    at Objects.clone (all.lwc.js:1431:39)
    at Objects.clone (all.lwc.js:1431:39)
```

This error occurs when the alignTo method merges configurations. The spec object includes target property, which is the original event that has taskBoardData property which contains a reference to the event, so the Objects.clone() method goes into infinite recursion.

I was able to narrow it down to a utility method named Objects.isObject() which checks whether a value is a plain object, not an instance of a class.

When LWS is on, it works correctly with Event and Element instances because those are real things wrapped in LWS Proxies. However, in Locker Service those same entities are represented by plain "secure" objects which is why they generate false positives.

The existing override for the isObject() method only checks if the value is a globalThis (window) reference before delegating to the original implementation. It needs to be modified to handle synthetic Event and Element instances in Locker.

The quickest and dumbest version of the new check involves "duck-typing" by checking if properties with certain names usual to Events or Elements can be found on the value. This may not be the optimal solution but it has been tested and worked.

```
{
    const EVENT_PROPS = ['type', 'isTrusted'];
    const ELEMENT_PROPS = ['tagName', 'innerHTML'];

    const isTypeOfObj = (obj) => typeof obj === 'object';
    const hasProps = (obj, props) => isTypeOfObj(obj) && props.every((prop) => prop in obj);

    const isLocker = () => !window.Worker;
    const isEvent = (obj) => isLocker() ? hasProps(obj, EVENT_PROPS) : obj instanceof Event;
    const isElement = (obj) => isLocker() ? hasProps(obj, ELEMENT_PROPS) : obj instanceof Element;

    class ObjectsOverrideIsObject {
      static get target() {
        return {
          class: Objects
        };
      }
      static isObject(obj) {
        return obj !== globalThis && !(isEvent(obj) || isElement(obj)) && this._overridden.isObject.call(this, obj);
      }
    }
    Override.apply(ObjectsOverrideIsObject);
}
```

We are going to apply this patch to our bundle but wondered if you may have some better ideas/solutions and whether there are plans to continue supporting 5.6.x in the nearest future?

Thanks!

**Comment by amurashincertinia** [comment]
I'd like to share an updated version of this override which we use in our custom bundle build.

```js
import { Objects } from '@bryntum/core-thin';

{
    // Property names found on an Event instance:
    const EVENT_PROPS = ['isTrusted', 'bubbles', 'composed'];

    // Property names found on an Element instance:
    const ELEMENT_PROPS = ['tagName', 'innerHTML', 'outerHTML'];

    const isTypeOfObj = (obj) => obj && typeof obj === 'object';

    const hasProps = (obj, props) => isTypeOfObj(obj) && props.every((prop) => prop in obj);

    // Worker constructor is not available in Locker Service
    const isLocker = () => !window.Worker;

    // Looks like an Event instance?
    const isEventLike = (obj) => isLocker() ? hasProps(obj, EVENT_PROPS) : obj instanceof Event;

    // Looks like an Element instance?
    const isElementLike = (obj) => isLocker() ? hasProps(obj, ELEMENT_PROPS) : obj instanceof Element;

    /*
     * When Lightning Web Security is switched off, the Locker Service
     * replaces Event and Element instances with plain object "secure"
     * versions of those instances, which causes Objects.isObject() to
     * return a false positive. The override here attempts to identify
     * those objects correctly using duck typing.
     */
    Objects.isObject = function isObject(obj) {
        return (
            !(obj === window || isEventLike(obj) || isElementLike(obj)) &&
            this._overridden.isObject.call(this, obj)
        );
    };
}
```

The changes are:
1. Different property names to check for on the object;
2. An "safety" `null`-check in the `isTypeOfObj` function.

**Comment by chuckn0rris** [comment]
Thank you for the help, Aleksei!
I will test it in our orgs shortly.

**Comment by amurashincertinia** [comment]
Hi there!

We've recently discovered that the override shared above is performing poorly in Lightning Web Security, unnecessarily hitting the membrane barrier (proxy). I'd like to suggest a few improvements:

1. The `isLocker` function should be a constant value. Toggling between `Locker` and `LWS` requires full page reload, so there is no way for the `Worker` global object to randomly disappear or reappear at run time.
```js
const isLocker = !window.Worker;
```

2. `isEventLike()` and `isElementLike()` helpers are only needed in `Locker`, so ternaries can be removed.
```js
const isEventLike = (obj) => hasProps(obj, EVENT_PROPS);
const isElementLike = (obj) => hasProps(obj, ELEMENT_PROPS);
```

3. The `isLocker` check should be moved from individual helpers to the `Objects.isObject` function body.
```js
Objects.isObject = function isObject(obj) {
    let isObj = true;

    if (isLocker) {
        isObj = !(obj === window || isEventLike(obj) || isElementLike(obj));
    }

    return isObj && this._overridden.isObject.call(this, obj);
}
```

Thanks.

**Comment by amurashincertinia** [comment]
Hi,

I noticed that you've tweaked your `isObject()` override in v7 (can't remember exactly which release, but the one in `7.2.1` looks much better.

So I believe this issue has been addressed and can be closed.

Thanks!
