### ISSUE TITLE
SchedulerPro realtime demo crashes

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#9591]
Unfortunately, I don't know what led to the problem. Perhaps Drag-create.

Yes, it is related to Drag-create. First drag-create worked on second attempt it crashed and then it crashes even on scrolling.

```
Uncaught Error: Method cannot be called at this state!
    at throwInvalidMethodCall (StateBase.js:11:11)
    at RevisionRecordingStateClass.onAutoRecordOff (RevisionRecordingState.js:101:9)
    at stateTransition (StateTrackingManager.js:48:26)
    at set autoRecord (StateTrackingManager.js:559:17)
    at EventDragCreate.captureStm (TaskEditStm.js:54:32)
    at EventDragCreate.captureStm (TaskEditTransactional.js:19:19)
    at EventDragCreate.dragStart (EventDragCreate.js:266:12)
    at EventDragCreate.startDrag (Draggable.js:515:29)
    at EventDragCreate.startDrag (DragCreateBase.js:174:30)
    at DragContext.start (DragContext.js:722:20)
424EventResize.js:925 Uncaught TypeError: Cannot read properties of undefined (reading 'offset')
    at EventDragCreate.moveDrag (EventResize.js:925:44)
    at EventDragCreate.trackDrag (Draggable.js:538:14)
    at DragContext.track (DragContext.js:774:16)
    at DragContext.move (DragContext.js:675:20)
    at EventDragCreate.onDragPointerMove (Draggable.js:760:19)
    at EventDragCreate.onDragPointerMove (EventResize.js:441:15)
    at HTMLBodyElement.handler (EventHelper.js:571:78)
DragCreateBase.js:246 Uncaught (in promise) TypeError: Cannot destructure property 'toSet' of 'context' as it is undefined.
    at EventDragCreate.dragDrop (DragCreateBase.js:246:15)
    at EventDragCreate.endDrag (Draggable.js:403:22)
    at EventDragCreate.onDragPointerUp (Draggable.js:770:18)
    at HTMLBodyElement.handler (EventHelper.js:571:78)
6DragCreateBase.js:246 Uncaught (in promise) TypeError: Cannot destructure property 'toSet' of 'context' as it is undefined.
    at EventDragCreate.dragDrop (DragCreateBase.js:246:15)
    at EventDragCreate.endDrag (Draggable.js:403:22)
    at DragContext.abort (DragContext.js:507:17)
    at EventDragCreate.onDragPointerDown (Draggable.js:743:18)
    at EventDragCreate.onDragMouseDown (Draggable.js:712:18)
    at HTMLDivElement.handler (EventHelper.js:571:78)
```

**Comment by bmblb** [comment]
Related ticket https://github.com/bryntum/support/issues/9492
