### ISSUE TITLE
Realtime updates demo crashes on login from second client

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#9593]
Login from the first client and quickly trying to login on the second client causing the crash.

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'split')
    at UsersContainer.handleWebSocketMessage (UsersContainer.js:23:35)
    at WebSocketProjectModel.trigger (Events.js:1543:44)
    at WebSocketProjectModel.handleWebsocketMessage (ProjectWebSocketHandlerMixin.js:189:12)
    at WebSocketManager.trigger (Events.js:1543:44)
    at WebSocketManager.onWsMessage (WebSocketManager.js:239:18)
```

**Comment by bmblb** [comment]
Dupe of #9592 
Parent issue https://github.com/bryntum/support/issues/9492
