### ISSUE TITLE
Crash when enabling LockRows and dragging selected events from both splits

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#9647]
http://lh/bryntum-suite/schedulerpro/examples/highlight-event-calendars/

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'assignmentRecord')
    at EventDrag.internalSnapToPosition (DragBase.js:143:41)
    at DragHelper.snapCoordinates (DragBase.js:236:20)
    at DragHelper.updateTranslateProxy (DragHelperTranslate.js:415:32)
    at DragHelper.startTranslateDrag (DragHelperTranslate.js:244:16)
    at DragHelper.internalMove (DragHelper.js:784:24)
    at DragHelper.onMouseMove (DragHelper.js:887:14)
    at HTMLDocument.handler (EventHelper.js:571:78)
```

**Comment by matsbryntse** [comment]
Also crash when selecting one record in both splits and dragging:
```

TypeError: Cannot destructure property 'id' of 'me.store.getAt(...)' as it is undefined.
    at RowManager.getRecordCoordsByIndex (RowManager.js:1056:15)
    at RowManager.getRecordCoords (RowManager.js:1039:19)
    at ProHorizontalRendering.getResourceEventBox (HorizontalRendering.js:364:52)
    at SchedulerPro.getResourceEventBox (SchedulerRegions.js:60:40)
    at ProHorizontalRendering.addTemporaryDragElement (HorizontalRendering.js:1340:25)
    at EventDrag.js:1667:59
    at Array.forEach (<anonymous>)
    at EventDrag.setupProductDragData (EventDrag.js:1663:27)
    at EventDrag.getDragData (DragBase.js:994:36)
    at EventDrag.getDragData (EventDrag.js:1721:22)
```
